### ISSUE TITLE
Attempt to cancel speech for expired focus events: issue closing messages in Thunderbird

### ISSUE THREAD

**Issue by amirsol81** [nvaccess/nvda#11492]
If NVDA's "Attempt to cancel speech for expired focus events" option is set to Yes in the Advanced tab of the Settings window, NVDA won't announce the name of the open/focused folder in Thunderbird 78 upon closing messages with Escape.
### Steps to reproduce:
1. Open Thunderbird, move to folder you want, say Inbox, and open a message.
2. Close the message with Escape.
### Actual behavior:
NVDA skips the announcement of the name of the folder, say inbox, and starts with "Property page ...". So the phrase "Inbox Mozilla Thunderbird", in the case of the Inbox folder, isn't announced.
### Expected behavior:
NVDA should first announce the name of the current/focused folder upon pressing Escape, like what it does when "Attempt to cancel speech for expired focus events" is set to No.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
Alpha 20725, but also duplicable with many alphas from the past couple of months
#### Windows version:
Win 10 Pro 64-Bit, Version 2004
#### Name and version of other software in use when reproducing the issue:
Thunderbird version 78.1.1
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Many alphas from the past couple of months
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
NA

**Comment by feerrenrut** [comment]
Could you please test this again for us with the [latest Alpha build](https://www.nvaccess.org/files/nvda/snapshots/), I suspect this is now resolved.

**Comment by amirsol81** [comment]
@feerrenrut Testing with the latest NVDA Alpha, the issue is still there but it has been sort of modified in a positive way. Now as soon as a message gets deleted, NVDA reads the message which gains focus -- I mean the subject of the next message. I think this is perfectly acceptable and the issue may be closed.

**Comment by lukaszgo1** [comment]
@amirsol81 Just to be extra clear is there still a difference in output when cancel speech for expired focus events is enabled versus disabled in Thunderbird?

**Comment by amirsol81** [comment]
@lukaszgo1 No, they are the same now.
