### ISSUE TITLE
UIA in Console: unable to access terminal after scrolling of long text

### ISSUE THREAD

**Issue by Andre9642** [nvaccess/nvda#11740]
### Steps to reproduce:
1. Ensure that "Use UI Automation to access the Windows Console when available" is enabled.
2. Open cmd or powershell.
3. Execute the follow line to generate some random text (you can use many other solutions for that like read a huge file using 'cat'):
   `wsl head -c 5000000 /dev/urandom|tr -dc "\u20-\u80"|fold -w80`
4. Wait until the previous command is finished (i.e. until the prompt is back).
5. Move in another window/go to desktop.
6. Return to cmd.

### Actual behavior:
We can't access to the Terminal content. No problem if UIA in Window Consoles is disabled.

### Expected behavior:
We should explore the Terminal.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-21145,ac31a795

#### Windows version:
Windows 10 Insider (64-bit) build 20231.1000

#### Name and version of other software in use when reproducing the issue:
cmd, powershell
#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If addons are disabled, is your problem still occuring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by codeofdusk** [comment]
This is microsoft/terminal#5481 (fixed in #11639). In future, when creating UIA console issues, please mention me (@codeofdusk) and @carlos-zamora. Thanks!

Technical: pre-21H1, UIA console ended each new line of text with a newline character (`\r\n`). Therefore, `_getTextLines` simply did a `splitlines` on all text. In 21H1, lines can wrap so this optimization is no longer sufficient.

**Comment by Andre9642** [comment]
Issue not fully solved for me (NVDA alpha-21312,cb82f504, Windows 10 Insider build 20251.1). It happens less often since #11639 was merged but still occurs. Tested with add-ons disabled.

**Comment by codeofdusk** [comment]
#11639 isn't in yet, but #11760 should've fixed this.

**Comment by codeofdusk** [comment]
Oh, never mind, I see what the issue is! This is a duplicate of #11002.

**Comment by Andre9642** [comment]
My bad. Thanks for the precision, I missed your issue.
