### ISSUE TITLE
NVDA in Microsoft Teams is repeatedly reading menu, chat landmark main region, and toggling browse mode on/off when navigating chat history

### ISSUE THREAD

**Issue by SMTestGH** [nvaccess/nvda#11783]
### Steps to reproduce:
1. Enable NVDA 2020.3
2. Enable Microsoft Teams
3. Press Ctrl+2 to move focus to Chats
4. select a chat from the list with arrow keys and enter
5. with focus in new chat edit box, press shift+tab
6.  Arrow up/down a few times in the chat history

### Actual behavior:
NVDA reads some combination of clickable, menu, chat landmark main region, and toggles browse mode on and off for reach message in the list. This makes NVDA way too verbose and adds extra time for consuming relevant information. If helpful, I can share a video file separately in email.

### Expected behavior:
NVDA reads the body of the message and who sent it.

#### NVDA installed/portable/running from source:
Installed locally

#### NVDA version:
2020.3, 2020.1, 2020.2

#### Windows version:
Windows 10 version 20H1, build 19042.572

#### Name and version of other software in use when reproducing the issue:
N/A

#### Other information about your system:
Note: only repros with NVDA (not JAWS or Narrator)

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Also reproduced in nvda 2020.1 and 2020.3

#### If addons are disabled, is your problem still occuring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by akash07k** [comment]
@SMTestGH 
I too can reproduce this issue and was thinking to file this issue but couldn't do it due to the time constraints.
I'm even using latest Alpha build and still the issue reproduces.
Thanks for filing this issue.
Actually, there's something with the latest teams updates because it was not reproducing some versions before. This issue started appearing since recent teams update I think around 1 month ago.
Anyways, it would be good if it could be fixed at NVDA's side as fixing it on teams' side can take a lot longer.
@SMTestGH  I think you are working with microsoft, can you please take up this issue with teams guys as well?

**Comment by michaelDCurran** [comment]
@SMTestGH The issue here is that The message list does not indicate to ATs that the list should be used in focus mode rather than browse mode. I.e. either the div with class ts-message-list-container, or the element of tag "message-list" should have an ARIA role of listbox if it is supposed to be an interactive list. Plus each indiviual list item, that gets focused, should have an ARIA role of 'option'.

It seems that other chat interface, exposed  in the new window after pressing the Chat Pop out button, has a similar problem, though it uses ul and li tags. Again, these should use ARIA roles of 'listbox' and 'option' respectively.

I'm not too sure what the issue with it saying "menu" is... it looks like we receive an EVENT_SYSTEM_MENUPOPUPSTART each time a message is focused. That issue may go away when correcting the roles... or perhaps each time a message is focus, a menu really is being created and or shown... which is bad.

It would also help if you provided your exact version of Teams you were testing with also. as Clearly Teams has changed significantly in the last month or so... new version of Chromium I think.

**Comment by SMTestGH** [comment]
Thanks, @michaelDCurran and @akash07k  yep - I'm with Microsoft's eDAD team and will follow up with the Teams engineering team on this. Thanks for the details!

There is a "menu" for a user to react and choose more options on a message, but it shouldn't be read out until a user presses enter to "interact" with the specific message. That could be what's coming into play here.

This repros on Teams version 1.3.00.29583, but with all the recent changes that may not be super indicative.

**Comment by munawarb** [comment]
I've been getting this issue as of a few days ago of this writing. It used to work fine in the past: you'd arrow up and down with focus mode on and then press Enter, when you'd be, as expected, in the options for the message. Now, arrowing up and down starts saying "menu" sometimes. I've noticed this even while composing a message: I'll be typing, and NVDA says "menu." Once it does this, "sayLine" no longer reads what I've typed so far. I have to re-focus the edit box to get the menu thing to go away so I can read my message again that I'm typing.

**Comment by leonardder** [comment]
This is related to #11821. The repetitive announcement of menu should be fixed by #11822

**Comment by seanbudd** [comment]
What is left on this issue now that #11822 is fixed - and perhaps other issues?

**Comment by munawarb** [comment]
@seanbudd We still have the issue of NVDA toggling out of focus mode when you get a  new message notification in Teams.

For example, when I'm arrowing up and down a message history and someone sends me a message, NVDA says "Browse mode" and my focus is suddenly restricted to the new message notification.

This happens while outside of Teams as well.

Also, #13799 Is still an issue.

**Comment by Adriani90** [comment]
@munawarb do you still have this issue  with the last Teams Update and the newest NVDA version?

**Comment by Adriani90** [comment]
I cannot reproduce this issue in Microsoft Teams 1.6.0 with NVDA 2022.4. I think this has been solved through a Teams update. Closing as works for me. Feeld free to comment in case you still have this issue.
