### ISSUE TITLE
Task: Update to latest (most appropriate) version of Python

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/nvda#12064]
- Update appveyor.yml
- Update to latest version of dependencies:
  - Scons
  - comtypes
  - wxPython
  - pySerial
  - py2exe
  - brltty

Initially Python 3.8 was being considered. 3.8 was chosen because 3.9 drops support for Windows 7 (see discussion: https://github.com/nvaccess/nvda/issues/10933#issuecomment-737709194). The plan was to upgrade to windows 3.8, give Windows 7 users early notice, then upgrade again a year later.

Instead, we ran into a bug in python which prevented updating: (see https://bugs.python.org/issue38748 and python/cpython#26204)

When this is resolved (at the next compat breaking release) we will update to the latest (most appropriate version of Python).
If this is not fixed, we may have to consider moving NVDA to 64 bit, (the bug does not affect 64 bit python). This would be a large and risky change.

**Comment by feerrenrut** [comment]
Fixed with PR Py3.8: Transparently use a Python virtual environment under the hood #12075

**Comment by lukaszgo1** [comment]
I'm not sure I fully understood your last comment @zstanecic but in short what I've proposed above was to stay on Python 3.7 but use the latest releases by building them from sources since Python developers are no longer releasing binary versions of Py 3.7. Also it seems to me you're  not realizing how serious the issue in libffi is - it affects much more than support for SAPI4 -  there is no way to learn in advance in which cases NVDA would crash as a result of this bug.

**Comment by mazen428** [comment]
Hello.
I think upgrading to python 3.8 in 2023 wouldn't make sense, because by then python 3.8 and even 3.9 would be considered old especially because they won't be getting any bug fixes, only security ones, so then we're back to the same issue.

**Comment by michaelDCurran** [comment]
The point is that we canot move off Python 3.7 before NVDA 2022.1 due to 
a stack corruption bug in Python.

Once this is addressed, we would move to what ever Python version seemed 
appropriate at the time.

**Comment by zstanecic** [comment]
Hi,

How it will be to tr to update to latest version and try it firstly in the try build, to see was this fixed?

Best,

Zvonimir

**Comment by feerrenrut** [comment]
@zstanecic We have added automated tests to python (see  https://bugs.python.org/issue38748 and python/cpython#26204) which show the issue, the problem is still not fixed.

I'll update the title of this issue to clarify.

**Comment by josephsl** [comment]
Hi,

2022 update: has anyone tried Python 3.11 alpha and see if latest libffi fixes the issue discussed here? If yes, I think 3.11 would be the most appropriate version to upgrade to in fourth quarter of 2022 (October at the earliest).

Thanks.

**Comment by mazen428** [comment]
Honestly I feel like NVDA should really be 64 bit, Microsoft no longer offers 32 bit ISOs for Windows 11, and as seen here NVDA now is stuck on a soon to be unsupported version of Python because of that, on top of that you have the 64 bit adobe crashes and a lot of other issues.

**Comment by josephsl** [comment]
Hi, I think perhaps that might be the next thing to do after investigating Python upgrade. Note that this will require preparations to support 32-bit NVDA add-ons, most notably speech synthesizers – this is the reason for existence of NVDA Remote Loader executable to handle 64-bit apps in certain scenarios. Thanks.

**Comment by leonardder** [comment]
The moment that Python 3.7 will be fully out of support is getting nearer and nearer. @feerrenrut could you please share NV Access' thoughts about this matter, especially given the Python team isn't paying any attention to this issue as it seems?

**Comment by josephsl** [comment]
Hi,

I might mention this in a new issue, but wxPython 4.2.0 does not come with Python 3.7 32-bit wheel - only 64-bit Windows and macOS builds are provided. This means we have to build that dependency ourselves via Appveyor (this takes time) or provide a wheel ourselves.

At this point, I think it would be much better to move to 64-bit provided that we are willing to come up with libraries to handle 32-bit x86, but we must also investigate ways to run x64 apps and libraries on Windows 10 on ARM64 (Windows 11 can be done easily thanks to x64EC). Bt if NVDA must stay as a 32-bit screen reader, then I think Python 3.11 would be a suitable candidate (meaning we must drop support for Windows 7 and 8.0; Python still supports Windows 8.1 for now).

Thanks.

**Comment by zstanecic** [comment]
What’s with the libffi issue and sapi4 corruption?

Note also that people still use old synths.

Best,

Zvonimir

**Comment by leonardder** [comment]
> I might mention this in a new issue, but wxPython 4.2.0 does not come with Python 3.7 32-bit wheel - only 64-bit Windows and macOS builds are provided. 

Are the wheels for Python 3.8+ X86 also missing?

> But if NVDA must stay as a 32-bit screen reader, then I think Python 3.11 would be a suitable candidate (meaning we must drop support for Windows 7 and 8.0; Python still supports Windows 8.1 for now).

I guess it is just too early to drop X86 support altogether. Having said that, this decision can be based on the usage stats as long as the code in updateCheck is fixed to report ARM explicitly.

**Comment by josephsl** [comment]
Hi, yes, no x86 (win32) 32-bit wheel for wxPython (testing wxPy 4.2.0 at the moment, the biggest change being InitLocale function behavior, so I think it would be safe to work on 4.2.0 upgrade whenever NV Access is ready). Thanks.

**Comment by lukaszgo1** [comment]
I'm not sure how 3.11 can be considered suitable candidate given that the libffi bug still occurs with this version. If it were only affecting SAPI4 then we may certainly drop support for it and update, but it also causes crashes for UIA under various versions of Windows and possibly some as of yet unknown crashes which can only be found by extensive testing.
As it stands I see 3 possibilities:
- Someone from NV Access or community or perhaps from Python fixes the bug for some future version of Python and we wait until that is done. Note that the EOL for Python 3.7 is not really relevant in our situation since we're stuck on the last binary release from August 2022 anyway, so we're already on an unsupported version for almost 2 years.
- Move to 64-bit - this requires a separate issue/discussion and frankly I'm not convinced this can be safely done in one release cycle.
- Move to 3.11  or whatever is the latest version rewriting known problematic components in C++ (for SAPI4 and UIA Handler this is perhaps manageable, but we still can experience some additional crashes after the release). Lack of WX Python wheels for x86 is not really a problem since we can easily compile it ourselves (I've tested that even for Python 3.7 this can be done, and while the build takes a long time if we would pre-compile it in advance that would not be noticeable).

As mentioned by Leonard it would be good to have a information about how many of our users are on 32-bit from someone at NV Access.

**Comment by zstanecic** [comment]
Well, 32 bit systems are one side of the medal, but what about the intercommunications between x86 apps on the 64 bit systems?

Best,

Zvonimir

**Comment by lukaszgo1** [comment]
> Well, 32 bit systems are one side of the medal, but what about the intercommunications between x86 apps on the 64 bit systems? 

That's why I've mentioned that migration to X64 would probably require way longer than one release cycle.

**Comment by josephsl** [comment]
Hi, moving from 32-bit to 64-bit (even with hybrid architecture approach) will be a complex operation – way more than Project Threshold, I think (Python 2 to 3 transition took more than a year to get it right). We could move to 64-bit, but remember that 32-bit add-ons will need an additional layer to talk to 64-bit nvda.exe, and most are speech synthesizers. I imagine by the time Windows 10 leaves consumer support (late 2025), 32-bit will be close to a thing of the past (there are folks still using 32-bit systems). Thanks.

**Comment by michaelDCurran** [comment]
Just answering the question about 32 bit daily usage: It is now just on 
5%. 95% are 64 bit.

**Comment by feerrenrut** [comment]
>The moment that Python 3.7 will be fully out of support is getting nearer and nearer. @feerrenrut could you please share NV Access' thoughts about this matter, especially given the Python team isn't paying any attention to this issue as it seems?

@leonardder We don't have a detailed plan for the upgrade to 64 bit python yet. We do have a few ideas for approaches we might take:
- Upgrading Python to a recent version will require dropping support for Windows 7. I suspect many of the users who are on a 32bit OS are on Windows 7.
- The quickest / smallest effort approach will be to drop support for 32 bit add-ons, this is probably our preferred approach at this stage. However, we will engage in community consultations before embarking down this path.
- Alternatives:
  - Fork libffi / Python, fix the issue and build it for use with NVDA. This likely has a high maintenance cost.
  - Upgrade to 64-bit python and build a 32-bit bridge for older add-ons. This will be a lot of work, and highly experimental.
  - Fix the issue in libffi directly, and petition the python devs to include it in the next python update.

**Comment by lukaszgo1** [comment]
>We don't have a detailed plan for the upgrade to 64 bit python yet. We do have a few ideas for approaches we might take:

Is this update to 64-bit going to at least be attempted for 2023.1? If so that is something that should be investigated sooner than later.

> 
>     * Upgrading Python to a recent version will require dropping support for Windows 7. I suspect many of the users who are on a 32bit OS are on Windows 7.

That can be easily verified with the update statistics you're collecting can it not?

> 
>     * The quickest / smallest effort approach will be to drop support for 32 bit add-ons, this is probably our preferred approach at this stage. However, we will engage in community consultations before embarking down this path.

That means dropping support for most commercially available speech synthesizers, so users won't be happy about this unless you provide some kind of a bridge (expecting add-on developers to write something like this themselves isn't reasonable). This also assumes that we won't hit some kind of a technical issues with NVDA itself during conversion - that is why I believe it is so important to have a  conversion plan as soon as possible.
Some areas worth to keep in mint:
- Some braille display drivers would probably have to be dropped
 - `wx.Accessible` is broken  in 64-bit and we need it for some components https://github.com/wxWidgets/Phoenix/issues/2010
 
>       * Fork libffi / Python, fix the issue and build it for use with NVDA. This likely has a high maintenance cost.
>       * Fix the issue in libffi directly, and petition the python devs to include it in the next python update.

This assumes someone at NV Access has necessary skills to do so. Have you investigated that path?

**Comment by valiant8086** [comment]
HI.


Maybe worth mentioning just as a general nudge nudge, I run all 64 bit 
machines because all the 32bit ones are gone, but I use a few 32bit only 
programs.


Cheers:
Aaron Spears, AKA Valiant8086 General Partner at Valiant Galaxy Associates "we make (VERY GOOD AUDIOGAMES) for the blind comunity" http://valiantGalaxy.com

**Comment by valiant8086** [comment]
Hi.


I for one rely heavily on a synth that has a 32bit dll. If it stopped 
working with NVDA, I'd stop updating NVDA and donating my monthly 5 
dollars. It sounds petulant, but ESpeak does not play nearly as nicely 
with my hearing aids.



Cheers:
Aaron Spears, AKA Valiant8086 General Partner at Valiant Galaxy Associates "we make (VERY GOOD AUDIOGAMES) for the blind comunity" http://valiantGalaxy.com

**Comment by dpy013** [comment]
[libffi](https://github.com/libffi/libffi/releases/tag/v3.4.3)
3.4.3 Sep-19-22
    All struct args are passed by value, regardless of size, as per ABIs.
    Enable static trampolines for Cygwin.
    Add support for Loongson's LoongArch64 architecture.
    Fix x32 static trampolines.
    Fix 32-bit x86 stdcall stack corruption.
    Fix ILP32 aarch64 support.

**Comment by dpy013** [comment]
[Feedback-bpo-38748: 32 bit ctypes stdcall callback fails to restore stack pointer ·](https://github.com/libffi/libffi/issues/727)
It should be fixed now.
[05785ca](https://github.com/libffi/libffi/commit/05785cafcf584d80c6b48651e1d33c4a3feca75c)
Can you please test with the HEAD of the master branch?

**Comment by leonardder** [comment]
It looks like, according to https://github.com/python/cpython/pull/26204#issuecomment-1256343863, the way is finally paved to consider a Python version update again.

**Comment by dpy013** [comment]
hi @josephsl  and @leonardder 
[bpo-38748: Add test for stack corruption. 26204](https://github.com/python/cpython/pull/26204)
[Update to libffi 3.4.3 96965](https://github.com/python/cpython/issues/96965)
[gh-96965: Update libffi in Windows release to 3.4.3 #97512](https://github.com/python/cpython/pull/97512)
and
[3.11 gh-96965: Update Windows release to libffi 3.4.3 (GH-97512) 97513](https://github.com/python/cpython/pull/97513)
The above [pull requests](https://github.com/python/cpython/pull) have all been merged
Also [python](https://github.com/python/cpython) official will provide the above pr patch in version 3.11
This is when NVDA needs to consider what windows 7 users should do?
thanks

**Comment by josephsl** [comment]
Hi, Python 3.11 no longer supports Windows 7 and 8.0, so anyone using 7 and 8.x should consider upgrading to Windows 10 sooner than later, today rather than tomorrow, this year rather than next year, ultimately comes down to what NV Access will say. Thanks.

**Comment by seanbudd** [comment]
We cannot update to Python 3.10 without updating wxPython to 4.2.0. wxPython 4.2.0 does not have a 32bit wheel, and we haven't confirmed that we can self compile 32 bit wheels for it. (refer to #12551)

**Comment by josephsl** [comment]
Hi, I can get it to work by downloading wxPython 4.2.0 via pip and running the installer. Also, I advise 3.11 as 3.9 may not include fixed libffi. Thanks.

**Comment by seanbudd** [comment]
>Hi, I can get it to work by downloading wxPython 4.2.0 via pip and running the installer. Also, I advise 3.11 as 3.9 may not include fixed libffi. Thanks.

Was this within the NVDA environment, i.e. a 32bit 3.7 interpreter?

**Comment by josephsl** [comment]
Hi, this was with Python 3.7 running from Command Prompt, and it appears wxPython wants attrdict as a dependency. Thanks.

**Comment by codeofdusk** [comment]
Why has the Python upgrade been deferred another year?

* If there are dependancy concerns, could the 2023.1 release be delayed to give sufficient time for dependancy updates and testing?
* Might it be possible to do the Python upgrade on a `threshold2` branch, issuing an (API-breaking) 2023.2/2023.3 release, as done for the last Python update? (see PR #9974).

**Comment by josephsl** [comment]
Hi,

Another showstopper: no wheels for py2exe designed for Python 3.11 at the moment (last checked: yesterday).

Thanks.

**Comment by leonardder** [comment]
@codeofdusk wrote:
> Why has the Python upgrade been deferred another year?

Where are you reading this?

@josephsl wrote:
> Another showstopper: no wheels for py2exe designed for Python 3.11 at the moment (last checked: yesterday).

Note that 3.11 is really fresh. Having said that, pretty sure @AlbertoSottile will jump on that train pretty quickly. I guess 3.11 neither has arrived on Appveyor.
I wonder whether they're planning to backport the libffi fix to Python 3.10.

In any case, another round of deferring the update would be very problematic, given that Python 3.7 is entirely out of support mid 2023.

**Comment by codeofdusk** [comment]
> Where are you reading this?

Both in the milestone of this issue (2024.1) and the explicit statement in https://github.com/nvaccess/nvda/issues/12551#issuecomment-1291210429.

**Comment by albertosottile** [comment]
> > Another showstopper: no wheels for py2exe designed for Python 3.11 at the moment (last checked: yesterday).

> Note that 3.11 is really fresh. Having said that, pretty sure @albertosottile will jump on that train pretty quickly. 

Your guess is sound, preliminary wheels are already available: https://github.com/py2exe/py2exe/issues/155.

**Comment by feerrenrut** [comment]
> Why has the Python upgrade been deferred another year?

For clarity I'm including some background on the decision.
We are postponing updating the Python version used in NVDA for the following reasons:
- There has been a bug in a component of Python (libffi) since Python 3.8. The bug is a showstopper for NVDA
- The libffi bug, has been fixed recently. The fix has been merged to Pythons main development branch, and to the 3.11 branch.
- The fix was merged too late to be included in the Python 3.11 release; it is very likely it will be included in the first patch release: Python 3.11.1
- The timing of the 3.11.1 release is not known.
- Changes to Python versions break NVDAs compatibility for add-ons, thus only happen in an NVDA YYYY.1 release, I.E., compatibility breaking releases.
- Updating the Python version in NVDA has a high degree of technical risk. It requires a long testing period to detect add address issues.
- Updating Python to 3.9 or later, requires dropping support for Windows 7. This should only happen after advanced warning for those users.
- Updating directly to 3.11.1 is riskier than updating to 3.8.X (only possible if the libffi fix is backported to 3.8), it will require an even longer testing period.
- Despite Python 3.7 no longer receiving updates, we aren't aware of known threats. This might change, and we would have to reconsider.
- It is expected that the Python version used with NVDA will be updated with the 2024.1 release. Which Python version is selected will depend on how far back the libffi fix is backported and on results of testing with various Python versions.
- Once the libffi fix is available in a Python release, a branch will be created to test / fix any issues with it. This will be a long-lived feature branch, with the goal of making the upgrade as stable as possible in preparation for an early merge into the 2024.1 dev cycle.

**Comment by josephsl** [comment]
­Hi, isn’t the libffi fix part of 3.11.0 released last week? That’s my impression, but even then, we have to think really carefully about dependencies. According to 3.10 changelog, the just included libffi fix will be part of a future 3.10.x release. Thanks

**Comment by josephsl** [comment]
Hi,

I take back my comment - yes, libffi 3.4.3 is not part of 3.11.0 final, and I expect 3.11.1 will be out in December at the earliest given 3.11 release schedule.

Thanks.

**Comment by josephsl** [comment]
Hi,

Indeed, Python 3.11.1 with the libffi update was released on December 6, 2022.

Thanks.

**Comment by dpy013** [comment]
> Hi,
> 
> Indeed, Python 3.11.1 with the libffi update was released on December 6, 2022.
> 
> Thanks.
cc @seanbudd 
[Changelog — Python 3.11.1](https://docs.python.org/release/3.11.1/whatsnew/changelog.html#python-3-11-1)

**Comment by feerrenrut** [comment]
This change log entry is in the Python 3.11.1 final release (Release date: 2022-12-06) in the [Windows section](https://docs.python.org/release/3.11.1/whatsnew/changelog.html#windows)
> [gh-96965](https://github.com/python/cpython/issues/96965): Update libffi to 3.4.3

**Comment by michaelDCurran** [comment]
We should also wait for pr python/cpython#100169 to reach a release as it addresses a separate bug with COM methods in 3.8+
See issue python/cpython#99952

**Comment by josephsl** [comment]
Hi all,

Good news - it appears the mentioned COM issue fix will be part of 3.11.2 based on latest changelog.

Thanks.

**Comment by Adriani90** [comment]
Here is what will be deprecated in python 3.12:
https://docs.python.org/3.12/whatsnew/3.12.html#pending-removal-in-python-3-14

Python 3.12 will finally arrive in October 2023, I guess it might make sense to update to that version and to keep an eye on Python 3.14 on a long term basis which is expected to become very fast.

In python 3.13 following will be deprecated:
https://peps.python.org/pep-0594/

**Comment by Adriani90** [comment]
Python 12 will also improve Garbage collection handling, hopefully this will also have a positive impact on NVDA:
https://github.com/python/cpython/issues/97922

**Comment by josephsl** [comment]
Hi,

September 2023 update: even though we have Python 3.11.x, I advise 3.12 (October 2023) as it is released after Windows 8.1's end of support and will allow us to update to binary releases until mid-2025 unless critical regressions with dependencies are found.

Thanks.

**Comment by leonardder** [comment]
@josephsl Could you please clarify your point about Windows 8.1? Will Python 3.12 still support Windows 8.1 including Server 2012 R2? Server 2012 R2 will receive extended security updates until 13 okt 2026.

**Comment by josephsl** [comment]
Hi, we have a precedent: Python 3.9 dropped support for Windows 7 and Server 2008 R2 despite Microsoft providing extended security updates. Python Software Foundation follows Microsoft’s support policy for Windows releases support. Thanks.

**Comment by lukaszgo1** [comment]
It would be really great to have a clear statement from NV Access regarding what versions of Windows they intent to support with the Python upgrade, and if the migration to 64-bit is even something they consider for 2024.1. I am also curious what is the point of  #15167 - as far as I can tell it merely duplicates content, and what we need is not a community discussion, but a clear announcement from NV Access. cc @seanbudd  @michaelDCurran

**Comment by leonardder** [comment]
I believe the standpoint has always been that NVDA only drops support for particular Windows releases when the used techniques force us to. That's the reason why Windows 7 is supported until now, even though it has been deprecated for a long time now. SO if Python 3.12 supports Windows 8.1, there is no reason for NVDA not to.

Re 64-bit NVDA, that will be a long journey. Quick research revealed that al ctypes calls involving pointer types would require explicit parameter annotations. ctypes seems to assume 4 bytes for a parameter by default, so throwing an 8 bit pointer will result in an OverflowError to be raised. It is probably way quicker to invest in custom wheel building when necessary for wxPython, for example.
While I don't want to scatter this issue wit X64 ramblings, I recall there was an issue dedicated to X64 switching but unfortunately I can't find it.

**Comment by seanbudd** [comment]
We'd like to update to python 3.11 as it is likely to be more stable/safer than 3.12 and we want to start work on updating python very soon. It should be easy enough to update to 3.12 in 2025.1 or later.

We don't plan on fully dropping win 8 support, as python and windows still support it, even though we are no longer making bug fixes.

Dropping 32bit support is not on the current roadmap as it is a massive rewrite.

>given several of our core dependencies are dropping X86 support for their wheels, a decision comes into view on this matter.

Could you give some examples here? wxPython has fixed this for now at least: https://github.com/wxWidgets/Phoenix/issues/2246#issuecomment-1582794435

**Comment by josephsl** [comment]
Hi, for Windows 8.x support, 8.1 or later is the way to go as 8.0 is no longer supported by Microsoft. Thanks.

**Comment by leonardder** [comment]
> Could you give some examples here? wxPython has fixed this for now at least: [wxWidgets/Phoenix#2246 (comment)](https://github.com/wxWidgets/Phoenix/issues/2246#issuecomment-1582794435)

I have missed that, I'm sorry. T
The only other dependency I know of is Py2exe. There are still X86 wheels, but they are untested. See https://github.com/py2exe/py2exe/discussions/157

**Comment by XLTechie** [comment]
Do we have to keep using py2exe? Could migrate to pyinstaller?

**Comment by leonardder** [comment]
I wasn't very happy with pyinstaller five years ago. See https://github.com/nvaccess/nvda/issues/8375#issuecomment-447064525

**Comment by XLTechie** [comment]
Interesting. I believe the library.zip issue is not a problem any more. The path 
thing, though ...

**Comment by mzanm** [comment]
What about Nuitka? It compiles to pyd and needs VS or another compiler though...

**Comment by leonardder** [comment]
I don't think switching away from py2exe is a serious point of discussion.

**Comment by lukaszgo1** [comment]
@leonardder  wrote:

> 
> Re 64-bit NVDA, that will be a long journey. Quick research revealed that al ctypes calls involving pointer types would require explicit parameter annotations. ctypes seems to assume 4 bytes for a parameter by default, so throwing an 64 bit pointer at it will result in an OverflowError to be raised. It is probably way quicker to invest in custom wheel building when necessary for wxPython, for example. While I don't want to scatter this issue wit X64 ramblings, I recall there was an issue dedicated to X64 switching but unfortunately I can't find it.



While I cannot find it either, it would be good to create one with your initial thoughts. Even though there are no current plans to switch to 64-bit, we would certainly have to do so at some point, and having list of documented problems way in advance should be pretty helpful.

**Comment by marlon-sousa** [comment]
Agreed, such an issue would be apreciated.
