### ISSUE TITLE
Often, entry into the python console causes modifier keys to stick

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/nvda#12348]
### Actual behavior:

I can't give an exact STR without describing the actual behavior, and because this problem is intermittent.

For the last many alphas (at least all since 2020.4, maybe before), entry into the python console causes the NVDA and control keys to stick.

For example: pressing NVDA+ctrl+z, waiting for the prompt to appear, and then starting to type "import", will cause first the mouse settings dialog to open, then the configuration profiles dialog.
Possibly after that, more typing will start interacting with the dialog, or the keys will continue to stick, which eventually leads to a config reversion once the "r" is reached.

[problem with python console log fragment.txt](https://github.com/nvaccess/nvda/files/6387993/problem.with.python.console.log.fragment.txt)

### Expected behavior:

Core doesn't freeze, the modifier keys release, the python console allows normal typing.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-22516,a0089a2f

#### Windows version:
Currently 20H2 (OS Build 19042.928),
but this has gone back at least through V2004.

#### Name and version of other software in use when reproducing the issue:

It might be relevant that this usually happens while Firefox is running, and possibly only while I'm focused on Firefox. However, I am not sure about that.
FF 84 through FF 88.

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Many, see above. I don't think this goes back before the post 2020.3 alpha sequence.

#### If add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by XLTechie** [comment]
cc @josephsl @michaelDCurran

**Comment by CyrilleB79** [comment]
I have sometimes encountered modifier keys remaining in down state for a long time (also before 2020.4) but not so often and not necessarily in the console.

In this case, I press all the modifiers one by one (both control, shift, alt and 3 NVDA) and things turn back normal.

Of course, it is not a solution.

**Comment by cary-rowen** [comment]
Yes, I have encountered this situation, but it is not easy to reproduce.

**Comment by JulienCochuyt** [comment]
I'm a huge NVDA Python Console user, can't remember a working day in the last 5 years or so without using it.
Faulty sticky modifiers key is something most intensive keyboard typist encounter more or less frequently, but I never could associate it with the opening of the NVDA Python Console.
I'm not stating the present report is wrong in its assumptions, but rather that there might potentially be outside factors influencing the odds of its occurrence in this very context.
FWIIW, as it seem the type of keyboard in use might influence the overall odds of faulty sticky modifiers keys, I'm most of the time typing on a TypeMatrix 2030.

**Comment by Adriani90** [comment]
@XLTechie are you still having this issue? If yes, it could be Related to #10588.

**Comment by XLTechie** [comment]
I think it is likely related, given @mltony's analysis of what's going on presented in that issue.

That issue has an additional complicating factor, so may require a solution from a different direction.

I don't have access to Win 10 right now, so can't easily test.

I haven't noticed this issue lately, but also haven't used the Python console much in recent months. So I would prefer to hear someone else's opinion of whether it's still happening, before deciding whether to close this. @CyrilleB79 @cary-rowen Your opinions?

Regarding @JulienCochuyt's question which I missed before: Usually a Compaq Internet keyboard, USB, through a USB KVM. But also through some other keyboards, including built-in keyboard, so I hesitate to blame the hardware.

**Comment by mltony** [comment]
I don't experience this particular problem with python console, but wanted to add my two cents regarding tracking keyboard modifiers state.
A couple of years ago I merged #12610 which fixes modifiers stuck problem to some extent. In my experience that PR reduced the number of times modifiers get stuck on my computer by 80 to 90%, but didn't get rid of the problem completely unfortunately.
I did some more investigation back then but didn't publish my conclusions, so let me try to reproduce them from my memory.

NVDA subscribes to all keyboard events in Windows  using WH_KEYBOARD_LL hook and for each key up or key down event it decides whether to forward it to the target app or to handle it internally within NVDA. However, if NVDA fails to process event within a given time frame (presumably 1 second), then Windows temporarily disables this hook.

from https://learn.microsoft.com/en-us/windows/win32/winmsg/lowlevelkeyboardproc

> The hook procedure should process a message in less time than the data entry specified in the LowLevelHooksTimeout value in the following registry key:
> HKEY_CURRENT_USER**\**Control Panel**\**Desktop
> The value is in milliseconds. If the hook procedure times out, the system passes the message to the next hook. However, on Windows 7 and later, the hook is silently removed without being called. There is no way for the application to know whether the hook is removed.
> Windows 10 version 1709 and later The maximum timeout value the system allows is 1000 milliseconds (1 second). The system will default to using a 1000 millisecond timeout if the LowLevelHooksTimeout value is set to a value larger than 1000.

So when NVDA is frozen, then keyboard modifiers can get out of sync almost by design. It makes some sense for typical applciations for sighted people: typical WH_KEYBOARD_LL applications would only listen for one or two specific keyboard events and if such an application freezes it wouldn't make sense to freeze the entire system.

Now let's think how can we fix this modifiers problem once and for all.
I can only come up with the idea of spawning another process, that would only handle subscribing to WH_KEYBOARD_LL hook and communicate with the main NVDA process using IPC. It will also never freeze. However I think when NVDA freezes we would need to implement some similar mechanism of passing keystrokes through, because sometimes when my NVDA freezes, I would want to either restart it by pressing contro+alt+N or launch Narrator or something. But this would require a lot of work and a blessing from NVAccess.

**Comment by CyrilleB79** [comment]
As written in https://github.com/nvaccess/nvda/issues/10588#issuecomment-2466780640, I still encounter the problem of blocked modifiers, even if quite rare. On my end it is not specifically related to the use of Python console.

But at least one issue related to blocked modifiers should remain open, even if it's a rare issue.
