### ISSUE TITLE
Embedded control's value not announced

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1282]
**Reported by simekk on 2010-12-18 17:36**
This issue is relevant for components that are embedded in title HTML tag. Using the sample code form the the ARIA specification at
http://www.w3.org/TR/wai-aria/complete#tac_example2:

```
<input type="checkbox" id="flash">
  <label for="flash">
    Flash the screen  
    <input type="text" value="3" size="2" id="numTimes"
           aria-label="Number of times to flash screen">
    times
  </label>
```

The control is embedded and according to the algorithm specified here:
http://www.w3.org/TR/wai-aria/complete#textalternativecomputation
in part 2B, the embedded input text field should present its value. But it doesn't. Instead the title is spoken, which ruins the idea of reading the current value in title.

Expected: Flash the screen 3 times 
I got:  Flash the screen Number of times to flash screen times 
("Number of times to flash screen" is a label)

Tested with IE8 or FF3.6.133 and leatest snapshot of NVDA
(JAWS 12 seems to handle this correctly but only with IE8)

**Comment by bhavyashah** [comment]
@jcsteh @feerrenrut Since this ticket seems to relate to ARIA, a key aspect of the ongoing Project Webfix, any thoughts/inputs?

**Comment by jcsteh** [comment]
I think there is an error in the original description, as it refers to the title tag, but I don't see how this is relevant. I'm guessing this was meant to refer to label. However, the point of the issue seems clear enough.

Quick test case: `data:text/html,<input type="checkbox" id="flash"><label for="flash">Flash the screen <input type="text" value="5" aria-label="Number of times to flash screen"> times</label>`

This still doesn't behave as expected in either Firefox or Chrome, but that needs to be fixed in the browsers. As for IE, there's no chance Microsoft will do anything, so we'd have to hack around it, which I don't think is something we will do given the difficulty in doing this and the ongoing demise of IE.

P3 to file bugs with Firefox and Chrome. Not something that hits users often in the wild as far as we know, so not a candidate for webfix.

**Comment by Adriani90** [comment]
@jcsteh is there already a bug filled with Mozilla?

**Comment by Adriani90** [comment]
Still reproducible with NVDA 2019.3 Beta 1, Firefox 71 and Chrome 79.

**Comment by aleventhal** [comment]
Fixed in Chrome Canary, starting tomorrow. See https://bugs.chromium.org/p/chromium/issues/detail?id=1121637

**Comment by Adriani90** [comment]
Thanks very much for the update @aleventhal. Very appreciated. So this is now still reproducible in Edge Chromium 85 and Firefox 80. I will adjust the labels accodingly.

**Comment by Adriani90** [comment]
Now the input value is spoken in all browsers, and in Firefox also the label and the input value is reported when focusing the checkbox.
Tested with 
NVDA Version alpha-24876,2325be89

EdgeVersion 99.0.1150.30
Chrome Version 99.0.4844.51
Firefox Version 97.0.2

Closing as works for me.
