### ISSUE TITLE
Word 365: NVDA does not report initial focus in Find and Replace dialog

### ISSUE THREAD

**Issue by bhavyashah** [nvaccess/nvda#13022]
### Steps to reproduce:
1 Open a new or existing Word document.
2 Press Ctrl+H to open the Find and Replace dialog.

### Actual behavior:
NVDA says "Find and Replace  dialog." It does not provide additional information on pressing NVDA+Tab or the read current line command.

### Expected behavior:
NVDA should report the opening of the Find and Replace dialog followed by the Find what field, on which focus initially lands. To be clear, the focus does land there because I can type something, Tab and Shift+Tab, and find what I typed as the contents of the Find what field.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
NVDA 2021.3 Beta 1
#### Windows version:
Windows 10
#### Name and version of other software in use when reproducing the issue:
Word for Microsoft 365
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by feerrenrut** [comment]
Can you confirm whether you have UIA for word enabled on the advanced settings panel?

**Comment by bhavyashah** [comment]
Yes, I have it enabled.

**Comment by feerrenrut** [comment]
Thanks, could you try with it disabled?

**Comment by bhavyashah** [comment]
I did. The issue persists.

On 11/3/21, Reef Turner ***@***.***> wrote:
> Thanks, could you try with it disabled?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/13022#issuecomment-960473481


-- 
Best Regards,
Bhavya Shah
Stanford University | Class of 2024
LinkedIn: https://www.linkedin.com/in/bhavyashah125/

**Comment by josephsl** [comment]
Hi,

Any updates in May 2022?

Thanks.

**Comment by bhavyashah** [comment]
This issue is reproducible in Word 365 using NVDA 2023.2 both with Word UIA set to "Always" and to "Only when necessary."

**Comment by Adriani90** [comment]
Still reproducible in MS Word 365 version 2509 with NVDA 2025.3.
I think this needs an external fix by Microsoft, the keyboard focus needs to be redirected properly to the coresponding control when opening the dialog.
cc: @msftedad can you please report this issue to the development team?

**Comment by msftedad** [comment]
@Adriani90, We have forwarded this issue to development team. We will provide you with the tracking id once we receive update from them. Thanks

**Comment by msftedad** [comment]
Issue shared with dependent team, for reference, team have created a ticket "[Accessibility 249491](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2FCSS-IRT%2FCSS%2520IRT%2F_workitems%2Fedit%2F249491&data=05%7C02%7Cv-ymounika%40microsoft.com%7C57cc96deafd644cfe83a08de126c1d3c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638968452732087808%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=BOFXQeIWYDoS4E4n21TJuctDNyTOc4BoZmOfwameVa8%3D&reserved=0)" tracking purposes, you won’t have access to this link, but this can be used as a reference number for this request.

**Comment by msftedad** [comment]
We have verified this in the latest build, NVDA correctly announces the opening of the Find and Replace dialog and indicates that the focus is on the “Find what” field. This behavior has also been verified with Narrator and JAWS.

Test Environment:
•	Windows 11 Enterprise Version 25H2 (OS build 26200.6899)
•	Microsoft Word for Microsoft 365 (Version 2510 Build 16.0.19328.20106) 64-bit
•	NVDA 2025.3.1
•	Narrator
•	JAWS 2025.2508.120

Please let us know if there are further questions. Thanks

**Comment by seanbudd** [comment]
Can anyone else confirm it is fixed in this version of Word?

**Comment by Adriani90** [comment]
@msftedad Here are my results while testing with NVDA 2025.3.1 and MS Word or Excel 365 version 2510 Build 16.0.19328.20178) 64 Bit

This issue is still reproducible:
1. Open MS Word
2. Press ctrl+h
3. Repeat these steps in MS Excel

Actual: NVDA reports that a window opens, but does not report the edit field in focus. NVDA reports e.g. "find and replace dialog".

Expected: NVDA should reoprt "find and replace dialog, search edit field".

**Comment by Adriani90** [comment]
@msftedad can you please forward my test results above to the development team?

**Comment by msftedad** [comment]
@Adriani90, Thank you for sharing the test results. We have forwarded them to the development team for their review and further action.
