### ISSUE TITLE
Accidentally disconnect USB cabled Seika Notetaker Braille display and reconnect needs restart NVDA

### ISSUE THREAD

**Issue by moyanming** [nvaccess/nvda#13143]
### Steps to reproduce:
1. Start NVDA 2021.3RC1
2. Connect the Seika Notetatker by USB cable
3. Select "Seika Notetaker" in the Braille display of NVDA and connect successfully.
4. Accidentally disconnect USB cable of Seika Notetaker.
5. Reconnect the USB cable of Seika Notetaker, but NVDA can't connect automatically.
6. Restart NVDA and Seika Notetaker connected automatically and works fine.

Here is the log [accidentally disconnect.log](https://github.com/nvaccess/nvda/files/7668636/accidentally.disconnect.log)
OSError: [WinError 1167] 设备没有连接。
"设备没有连接" means the device is not connected.

#### Windows version:
Windows 10 1901 Pro

**Comment by moyanming** [comment]
I have tested [this build](https://ci.appveyor.com/api/buildjobs/h89xxrp7yoee8air/artifacts/output%2Fnvda_snapshot_pr13156-24338%2C9b0d2467.exe), but this issue has not been fixed yet.
Here is the log:
[accidentally disconnect.log](https://github.com/nvaccess/nvda/files/7692462/accidentally.disconnect.log)

**Comment by seanbudd** [comment]
Is this fixed in 2022.1? Was this fixed by https://github.com/nvaccess/nvda/pull/13191, https://github.com/nvaccess/nvda/issues/13142?

**Comment by cary-rowen** [comment]
@seanbudd 
Hello, I tested with the latest alpha-25756 and it is not fixed.

**Comment by moyanming** [comment]
> Is this fixed in 2022.1? Was this fixed by #13191, #13142?

Hi @seanbudd 
I have tested NVDA 2022.2 and this issue is not fixed yet.

**Comment by CyrilleB79** [comment]
@moyanming, there has been a significant rework of brialle in last NVDA versions. Is this issue still present?

**Comment by moyanming** [comment]
> @moyanming, there has been a significant rework of brialle in last NVDA versions. Is this issue still present?

Hi @CyrilleB79 ,
I have tested the Seika Notetaker with NVDA 2024.1, this issue still no fixed.

**Comment by Adriani90** [comment]
@moyanming, @school510587 is this still an issue with NVDA 2025.1 Beta and Seika braille displays?

**Comment by school510587** [comment]
Hi,

Sorry, I have no chance to use any Seika braille display recently. Thus, I cannot answer the problem.

**Comment by Adriani90** [comment]
I am closing this issue as abandoned due to missing updates since more than one year. If you are still having this problem, please comment with new test results and we can reopen.

**Comment by cary-rowen** [comment]
@Adriani90

I am writing to formally object to your decision to close this issue.

Your justification for closing this as "abandoned" seems to misapply the label's own description, as I provided an update confirming the issue still exists on Jul 8, 2022. You also closed this only hours after requesting a new test, which is not a reasonable timeframe for a community member to respond.

This brings up a broader question: could you please point to the official NV Access policy that dictates when a triaged issue should be considered abandoned? I am not aware of a formal public policy on this, and arbitrarily closing confirmed bugs seems counterproductive. There are over two thousand open issues, and I am certain many with three-digit numbers remain open without updates for far longer. The inconsistent application of this 'abandoned' rule is concerning for the health of the issue tracker.

As I no longer own the Seika hardware, I have been asking others to help re-test, but it is difficult due to geographical distance. However, my inability to provide a new log file at this exact moment does not invalidate my last report which confirmed the bug was still present.

As an active contributor, I frequently submit new issues and also take care to close those I can personally verify have been resolved. I believe your action here is disruptive.

I respectfully request that you reopen this issue.

**Comment by cary-rowen** [comment]
Furthermore, you closed this issue with the status "not planned." This action is in direct contradiction with your own comment stating it was closed for being "abandoned." More importantly, I do not believe you have the authority to apply the "not planned" status, as this implies a final, official decision from the core NV Access team that this bug will not be fixed.

**Comment by SaschaCowley** [comment]
We have no indication that this issue has been resolved. The information here is clear and verifies the issue. This issue should only be closed when we have evidence that the problem has been fixed or no longer applicable to NVDA.
