### ISSUE TITLE
unusual behavior of repeatedly connecting Seika Notetaker

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#13243]
I've only reproduced the issue with Seaka devices, so I don't know how other braille devices will perform.

### Steps to reproduce:
1. Connect Seika Notetaker to PC via USB cable or Bluetooth;
2. Press NVDA +Ctrl +A to open the braille device selection dialog and select Seika Notetaker
3. Then press the "OK" button;
4. Repeat steps (2) and (3).

### Actual behavior:
- Perform steps (1), (2), (3) the device works as expected
- Perform step 4, the device display is blank, there is no braille output

### Expected behavior:
When we do step (4), a more reasonable situation should be to display braille normally.

#### NVDA installed/portable/running from source:
installed, portable and running 

#### NVDA version:
- The connection of the USB cable was tested with 2021.3.1
- Tested both USB and Bluetooth connectivity with the latest build in #13191

#### Windows version:
Windows 10 21H2 (x64) build 19044.1466
#### Name and version of other software in use when reproducing the issue:
None
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
None
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by seanbudd** [comment]
Is this fixed in 2022.1? Was this fixed by #13191, #13142?

**Comment by cary-rowen** [comment]
Hello, I tested with the latest alpha-25756 and it is not fixed.
Below is the log:
[nvda-log.txt](https://github.com/nvaccess/nvda/files/9067960/nvda-log.txt)

**Comment by CyrilleB79** [comment]
@cary-rowen there has been an important rework of braille in the last versions of NVDA. Is the issue still present?

**Comment by cary-rowen** [comment]
Hi @CyrilleB79 
I don't have the seika device to test this yet.
I'll update this if I find anything new.

**Comment by Adriani90** [comment]
@cary-rowen any updates on this with NVDA 2024.4.1? Is there anyone in the chinese community maybe who has a braille display to test with?

**Comment by Adriani90** [comment]
No updates from the initial author upon request since more than one year, closing as abandoned. If you are still having this issue, please comment and we can reopen.

**Comment by cary-rowen** [comment]
cc @Adriani90 
I haven't had the chance to get the device for testing this issue, but it's been on my to-do list, please don't close it arbitrarily.  You wrote "No updates from the initial author upon request since more than one year". Please clarify your basis for this? Is this NV Access's attitude? If so, how many of the more than two thousand issues are inactive for over a year, and should they all be closed?

**Comment by cary-rowen** [comment]
Checking the latest status of an issue is always welcome, but it also puts pressure on the original reporter.  If possible, I'd prefer to see your requests for updates be justified, such as which commits might affect it, and which PRs might improve it.

**Comment by Adriani90** [comment]
Well, providing an updated status  once a year or so is not a huge expectation imo. We repeatedly requested updates and they were not provided. That‘s what happens since many years with issues like this one. Be sure that I would be the first one reopening such issues if the users who can reproduce are still having the issue. The last real status update is almost 3 years old. And by the way, I never close issues without asking people for updates first, or without trying to reproduce myself where possible. But yeah, we have now status updates on most of the 2.1k open issues. And this helps in making progress. It‘s about joining forces, not about refusing cooperations.  Thanks for your understanding, and I think you are a great contributor to this project, don‘t get me wrong. But this issue is treated the same as all other issues where repro status is missing upon request since more than 1 year.
