### ISSUE TITLE
libreoffice calc auto filter drop down list is not spoken

### ISSUE THREAD

**Issue by ilyapashuk** [nvaccess/nvda#14474]
### Steps to reproduce:

1. open any sheet in the libreoffice calc
2. select the range for filtering
3. type ctrl+shift+l to enable the auto filter
4. select heading of the any column
5. press alt+down to open the dropdown list

### Actual behavior:

nothing is spoken after alt+down, nothing is spoken when mooving the arrow keys, User can do nothing until dropdown list is closed by the esc key.
### Expected behavior:

opened dropdown list should be readable by the nvda.
#### NVDA installed/portable/running from source:
nvda installed
#### NVDA version:
2022.2
#### Windows version:
windows 10 enterprise ltsc 1809 64 bit
#### Name and version of other software in use when reproducing the issue:
libreoffice 7.3
#### Does the issue still occur after restarting your computer?
yes
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by michaelweghorn** [comment]
This was just fixed in LibreOffice, see https://bugs.documentfoundation.org/show_bug.cgi?id=152671 , so I guess this issue can be closed.

CC @Adriani90

**Comment by Adriani90** [comment]
Can still reproduce here with NVDA alpha-27818,fa89f058 (2023.2.0.27818)
and Libreoffice calc 7.5.1

Following is written to NVDA's log:

```
IO - inputCore.InputManager.executeGesture (14:39:21.050) - winInputHook (5248):
Input: kb(laptop):upArrow
DEBUG - NVDAObjects.IAccessible.IAccessible.getSelectedItemsCount (14:39:21.100) - MainThread (21380):
Cannot fetch selected items count using accSelection, 
DEBUG - NVDAObjects.IAccessible.IAccessible.getSelectedItemsCount (14:39:21.100) - MainThread (21380):
Cannot fetch selected items count using accSelection, 
IO - speech.speech.speak (14:39:21.120) - MainThread (21380):
Speaking ['Land', 'B1']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._getIA2RelationFirstTarget (14:39:21.120) - MainThread (21380):
Unable to use _getIA2TargetsForRelationsOfType, fallback to _IA2Relations.
IO - inputCore.InputManager.executeGesture (14:39:21.483) - winInputHook (5248):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (14:39:21.928) - winInputHook (5248):
Input: kb(laptop):downArrow
DEBUG - NVDAObjects.IAccessible.IAccessible.getSelectedItemsCount (14:39:21.975) - MainThread (21380):
Cannot fetch selected items count using accSelection, 
DEBUG - NVDAObjects.IAccessible.IAccessible.getSelectedItemsCount (14:39:21.975) - MainThread (21380):
Cannot fetch selected items count using accSelection, 
IO - speech.speech.speak (14:39:21.990) - MainThread (21380):
Speaking ['B2']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._getIA2RelationFirstTarget (14:39:21.990) - MainThread (21380):
Unable to use _getIA2TargetsForRelationsOfType, fallback to _IA2Relations.
IO - inputCore.InputManager.executeGesture (14:39:22.136) - winInputHook (5248):
Input: kb(laptop):upArrow
DEBUG - NVDAObjects.IAccessible.IAccessible.getSelectedItemsCount (14:39:22.172) - MainThread (21380):
Cannot fetch selected items count using accSelection, 
DEBUG - NVDAObjects.IAccessible.IAccessible.getSelectedItemsCount (14:39:22.176) - MainThread (21380):
Cannot fetch selected items count using accSelection, 
IO - speech.speech.speak (14:39:22.186) - MainThread (21380):
Speaking ['Land', 'B1']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._getIA2RelationFirstTarget (14:39:22.186) - MainThread (21380):
Unable to use _getIA2TargetsForRelationsOfType, fallback to _IA2Relations.
IO - inputCore.InputManager.executeGesture (14:39:24.407) - winInputHook (5248):
Input: kb(laptop):alt+downArrow
DEBUGWARNING - IAccessibleHandler.internalWinEventHandler._shouldGetEvents (14:39:24.485) - MainThread (21380):
Foreground took too long to change. Foreground still 788486 (SALFRAME). Should be 1182714 (SALTMPSUBFRAME)
IO - inputCore.InputManager.executeGesture (14:39:26.165) - winInputHook (5248):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (14:39:27.022) - winInputHook (5248):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (14:39:28.491) - winInputHook (5248):
Input: kb(laptop):NVDA+f1
```

**Comment by michaelweghorn** [comment]
> Can still reproduce here with NVDA alpha-27818,fa89f058 (2023.2.0.27818) and Libreoffice calc 7.5.1

The LibreOffice fix was merged this morning, so isn't contained in 7.5.1. You'd need a current development build of LibreOffice, e.g. a daily build from https://dev-builds.libreoffice.org/daily/master/current.html once a new one is available there (presumably by tomorrow).

**Comment by seanbudd** [comment]
Closing as fixed
