### ISSUE TITLE
NVDA can't read Data Validation drop down in Excel 365

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#15138]
### Steps to reproduce:
1) Have NVDA and Excel running :)
2) In a blank cell, press alt, a, v, enter to open data validation
3) Tab to "Allow" and select "List".
4) Tab to "Source" and type:
1, 2, 3
5) Press enter to save the data validation.
6) Navigate away from and back to the cell with data validation
7) Press alt+down arrow to open the drop down list (which should contain the options 1, 2, and 3).
8) down arrow through the list.

### Actual behavior:

At Step 6, NVDA reports the "Submenu"
At Step 7, the menu opens but nothing is reported
At step 8, NVDA only reports "Submenu A1" (Where "A1" is the coordinates of the cell you are using)

### Expected behavior:

NVDA should report the current list item while moving through the list.

### NVDA logs, crash dumps and other attachments:

Logs with and without UIA enabled for Excel (the only difference is that with UIA enabled, NOTHING is reported when down arrow is pressed in the list.  Without UIA enabled, NVDA reports the submenu again, but not the list item.

[DataValidationWithoutUIA.txt](https://github.com/nvaccess/nvda/files/12046020/DataValidationWithoutUIA.txt)
[DataValidationWithUIA.txt](https://github.com/nvaccess/nvda/files/12046021/DataValidationWithUIA.txt)

#### NVDA version:
alpha-28643,03033ba6 installed

Also tried the current alpha-28675,384a7428 and NVDA 2023.1 with same results.

#### Windows version:

Windows 11 (64-bit) Version: 22H2, Build: 22621.1992 

#### Name and version of other software in use when reproducing the issue:

Office 365 (64-bit) Version: 16.0.16529.20118 

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

As above

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes

**Comment by Qchristensen** [comment]
The only workaround I can find is that you CAN select items in the data validation list, you just don't get any feedback until you do:

1) Press alt+down arrow to open the list.
2) The first time you open this, the first item will be selected.  After that, press down arrow once to move to the next item.
3) Press ENTER to select the item and close the drop down.
4) NVDA will then read the item which is selected.  If this is not the desired item, repeat from step one above.

(Also reported to Microsoft today 14/07/2023)

**Comment by michaelDCurran** [comment]
Note that the data validation list (which does not work) is different to the auto complete combo box (E.g. choosing a value from above cells) which does still work.

Technical:
For the data validation list:
Via both UIA and MSAA, Excel fires focus and selection events on list items within a standard SysListview32 control.
NVDA ignores UIA and falls back to MSAA, as the window in question reports that it is non-native UIA (I.e. IsServersideProvider returns 0).
However, although Excel fires MSAA events for focus and selection, it does not allow fetching of valid MsAA object for them. I.e. AccessibleObjectFromEvent returns E_UNEXPECTED when giving it the event parameters for those events.
To solve this, either:
* Excel needs to mark this window as being native UIA, or
* Excel needs to stop refusing to create MSAA objects for this window, or
* NVDA needs to explicitly treat this window as supporting UIA.

**Comment by zstanecic** [comment]
Hi,

I am for crowdin, but how we will proceed with current documentation then?

It is not an easy solution when it goes to switch. It cannot happen overnight.

**Comment by seanbudd** [comment]
@zstanecic  - you have replied to the wrong issue

**Comment by gauravahir28** [comment]
Is there a possibility of resolving this issue in NVDA 2023.2? I'm aware of many NVDA users who are experiencing this issue. The dropdowns seem to function correctly with Narrator. This problem is making it difficult to transition between Narrator and NVDA due to this issue.

**Comment by Adriani90** [comment]
This issue must have appeared in a recent build of MS Office 365. Not sure if it has an impact on this, but does it occur also when selective registering for UIA events is disabled in NVDA's advanced settings?

**Comment by gauravahir28** [comment]
I was unable to locate the "Disabled" option within the "selective registering for UIA events" settings. Despite trying all the available options [ "Global," "Selective," and "Automatic" ] the problem persists.

**Comment by cary-rowen** [comment]
@Adriani90 wrote:
> This issue must have appeared in a recent build of MS Office 365. Not sure if it has an impact on this, but does it occur also when selective registering for UIA events is disabled in NVDA's advanced settings?

Yes!

**Comment by gauravahir28** [comment]
Is there any possibility of getting this fixed in 2024.1? Just for the dropdowns, switching between Narrator and NVDA is impacting productivity a lot!

**Comment by Adriani90** [comment]
I strongly second this! Can it be prioritized please? In Office 2016 it still works, but soon the company I work for will change to Office 365 and this will make my job almost impossible because I work with a lot of Excel sheets and the Windows 10 version is quite old. Narator does not work with Excel well enough in that Windows 10 version.

**Comment by Adriani90** [comment]
It seems also Jaws works as expected. So it is definitely an NVDA issue but there is no regression. i tested with NVDA until 2019.2 and the issue was still occuring. It seems a Microsoft Office update broke something with regard to how NVDA accesses this information on dropdown validation data.

**Comment by britechguy** [comment]
I am also reporting that I can replicate this issue today with NVDA 2023.3 and Microsoft® Excel® for Microsoft 365 MSO (Version 2312 Build 16.0.17126.20132) 64-bit, with Excel having been freshly updated as of this morning.

My bit of added data here is that NVDA can see the individual values when the data validation is expanded via mouse tracking.  As I move the mouse pointer over the list items, they are announced.  But if I expand the list and use up/down arrow to traverse it, the options are not announced and I get something like, "Submenu, C3" where th C3 is whatever cell the validation list happens to be attached to as I move item by item.

This is a pretty "mission critical" fix for users of NVDA with Microsoft Excel 365.

**Comment by gauravahir28** [comment]
Could this be  prioritize this, please? @seanbudd 
Dropdown options seem to have a party whenever the narrator is around, announcing their presence loud and clear. As mentioned earlier, this is seriously putting a dent in our productivity!

**Comment by jmdaweb** [comment]
Hi,
Any news on this? It's essential for a11y consultants to fill in some reports which must be in a speciffic format.
Regards.
CC: @jpavonabian

**Comment by cary-rowen** [comment]
cc @michaelDCurran 
It seems that this issue has been investigated.

**Comment by Anant5000** [comment]
Any updates on this? 
As mentioned before, this is severely affecting productivity!
CC @seanbudd @michaelDCurran @SaschaCowley

**Comment by gauravahir28** [comment]
Any updates on this?
As mentioned before, this is severely affecting productivity!
CC @seanbudd @michaelDCurran @SaschaCowley

**Comment by Adriani90** [comment]
This is what I get in my log file when trying to navigate the values in the dropdown:
```
IO - speech.speech.speak (10:22:52.739) - MainThread (19516):
Speaking ['B3', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (10:22:53.028) - winInputHook (9024):
Input: kb(laptop):downArrow
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (10:22:53.048) - MainThread (19516):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_SELECTIONREMOVE, window 986096 (EXCEL7), objectID 574, childID 0, process 13532 (excel), thread 4356
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (10:22:53.048) - MainThread (19516):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_SELECTION, window 986096 (EXCEL7), objectID 575, childID 0, process 13532 (excel), thread 4356
DEBUG - IAccessibleHandler.internalWinEventHandler.winEventCallback (10:22:53.048) - MainThread (19516):
Dropping UIA proxied event for Excel7 window. WinEvent: EVENT_OBJECT_FOCUS, window 986096 (EXCEL7), objectID 576, childID 0, process 13532 (excel), thread 4356
DEBUG - NVDAObjects.window.excel.ExcelWorksheet.script_changeSelection (10:22:53.069) - MainThread (19516):
Detected new selection after 0 sec
IO - speech.speech.speak (10:22:53.078) - MainThread (19516):
Speaking ['Untermenü', 'B4', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (10:22:53.478) - winInputHook (9024):
Input: kb(laptop):alt+downArrow
DEBUGWARNING - NVDAObjects.window.excel.ExcelBase._getDropdown (10:22:53.512) - MainThread (19516):
Could not locate dropdown list in previous objects
DEBUGWARNING - NVDAObjects.window.excel.ExcelBase._getDropdown (10:22:53.558) - MainThread (19516):
Could not locate dropdown list in previous objects
DEBUGWARNING - NVDAObjects.window.excel.ExcelBase._getDropdown (10:22:53.587) - MainThread (19516):
Could not locate dropdown list in previous objects
DEBUGWARNING - NVDAObjects.window.excel.ExcelBase._getDropdown (10:22:53.635) - MainThread (19516):
Could not locate dropdown list in previous objects
DEBUGWARNING - NVDAObjects.window.excel.ExcelBase._getDropdown (10:22:53.668) - MainThread (19516):
Could not locate dropdown list in previous objects
DEBUGWARNING - NVDAObjects.window.excel.ExcelBase._getDropdown (10:22:53.698) - MainThread (19516):
Could not locate dropdown list in previous objects
DEBUGWARNING - NVDAObjects.window.excel.ExcelBase._getDropdown (10:22:53.737) - MainThread (19516):
Could not locate dropdown list in previous objects
DEBUGWARNING - NVDAObjects.window.excel.ExcelCell.script_openDropdown (10:22:53.766) - MainThread (19516):
Failed to get dropDown, giving up
IO - inputCore.InputManager.executeGesture (10:22:54.073) - winInputHook (9024):
Input: kb(laptop):downArrow
DEBUG - NVDAObjects.window.excel.ExcelWorksheet.script_changeSelection (10:22:54.241) - MainThread (19516):
Canceled detecting new selection after 0.16113877296447754 sec
IO - speech.speech.speak (10:22:54.253) - MainThread (19516):
Speaking ['Untermenü', 'B4', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (10:22:54.590) - winInputHook (9024):
Input: kb(laptop):downArrow
DEBUG - NVDAObjects.window.excel.ExcelWorksheet.script_changeSelection (10:22:54.758) - MainThread (19516):
Canceled detecting new selection after 0.15018224716186523 sec
IO - speech.speech.speak (10:22:54.768) - MainThread (19516):
Speaking ['Untermenü', 'B4', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (10:22:56.658) - winInputHook (9024):
Input: kb(laptop):rightArrow
DEBUG - NVDAObjects.window.excel.ExcelWorksheet.script_changeSelection (10:22:56.828) - MainThread (19516):
Canceled detecting new selection after 0.15992355346679688 sec
IO - speech.speech.speak (10:22:56.833) - MainThread (19516):
Speaking ['Untermenü', 'B4', CancellableSpeech (still valid)]
```

This is getting annoying since many companies switch to MS 365 and many Excel files become inaccessible. @SaschaCowley can you please give some official advise from NV Access on how costly this is to fix? Does it need an external fix?
cc: @Qchristensen.
cc: @msftedad in case it needs something from Microsoft for this to work properly. It really stops people from doing their job.

**Comment by msftedad** [comment]
Hi @Adriani90 - We are checking this case, will update with progress here.
