### ISSUE TITLE
NVDA crashes with Google Chrome

### ISSUE THREAD

**Issue by alexstine** [nvaccess/nvda#15550]
### Steps to reproduce:
1. Start NVDA.
2. Open a website with a lot of Google ads or lots of content. This one for example.
https://react.dev/reference/react-dom/createPortal
3. Navigate to the link titled "key". Direct link below.
https://react.dev/learn/rendering-lists#keeping-list-items-in-order-with-key
4. Notice how Google Chrome crashes.

### Expected behavior:

Google Chrome should not crash and NVDA shouldn't require a restart.

### NVDA logs, crash dumps and other attachments:
Attached.

#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
2023.2 (2023.2.0.29051).
#### Windows version:
10.0.19045 Build 19045
#### Name and version of other software in use when reproducing the issue:
Google Chrome: 117.0.5938.92 (Official Build) (64-bit)
#### Other information about your system:
Architecture: 64-bit
#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.
#### If NVDA add-ons are disabled, is your problem still occurring?
Have not tested.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

This also happens on my work computer which has similar specifications.

[debug.log](https://github.com/nvaccess/nvda/files/12753995/debug.log)

**Comment by seanbudd** [comment]
Have you reported this to Google or chromium yet?

If you are comfortable with the more technical GitHub style reporting, you can file an issue directly with their issue tracker: https://www.chromium.org/for-testers/bug-reporting-guidelines/reporting-crash-bug/

**Comment by alexstine** [comment]
@seanbudd I'll report it to Google tomorrow. I've written up a couple things on their Monorail and it is usually where accessibility goes to die so wanted to make sure there was nothing that could be done on NVDA side first.

Thanks. 👍

**Comment by seanbudd** [comment]
There's a crash fixed in Chrome 119 (canary). It might be worth testing with chrome canary as well.

If the issue is with NVDA, the chromium team might still be better placed to debug the crash and provide technical information

**Comment by Brian1Gaff** [comment]
You should still have the old log. However, I noticed a similar problem on Waterfox classic. Sometimes in such cases you can do an alt ctrl delete and instead of logging off, take cancel, and the nvda will come back. Brian

-- 
***@***.*** 
Sent via blueyonder.(Virgin media) 
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.

**Comment by alexstine** [comment]
@seanbudd https://bugs.chromium.org/p/chromium/issues/detail?id=1488435

@Brian1Gaff NVDA totally crashes. Not even the old Control+Alt+Delete and Cancel trick works. It doesn't always happen though, so weird.

**Comment by Adriani90** [comment]
@alexstine this seems fixed in Chrome 118 with NVDA last alpha version according to my tests. I am closing this issue for now, please comment on the Chromium bug that you referenced above in case you are still having this issue with Chrome 118.
