### ISSUE TITLE
NVDA not reporting Window Title when navigating tabs in Vivaldi Browser (possibly others, but not Edge or Brave)

### ISSUE THREAD

**Issue by britechguy** [nvaccess/nvda#15606]
### Steps to reproduce:
Open Vivaldi Browser and create multiple tabs.
Use F6 to gain focus on the tabs then left and right arrow through them.  Each is announced as "clickable."

### Actual behavior:
Noted in steps to reproduce.  For Edge and Brave, both announce the webpage title as one moves along the tabs.

### Expected behavior:
That page titles for the respective tabs be announced when traversing the tabs.  This could very well be a Vivaldi issue, but I can't be certain.

#### NVDA installed/portable/running from source:  
Installed for Vivaldi & Edge testing, portable for Brave testing

#### NVDA version:
2023.3.beta3
#### Windows version:
Windows 11 Version 22H2
#### Name and version of other software in use when reproducing the issue:
Vivaldi 6.2.3105.58 (Stable channel) (64-bit) 
#### Other information about your system:
Both systems used for testing are LG Gram 16 laptops, one has an i5 12th gen CPU, the other an i7 11th gen.
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by Nael-Sayegh** [comment]
Hello,
Have you tried to see if this problem occurs with other screen readers?
Have you always had this issue, or did it start after an update to NVDA, Windows, or something else?

**Comment by britechguy** [comment]
> Have you tried to see if this problem occurs with other screen readers?

No, I have not.  Since it is only happening with the Vivaldi browser, but not other Chromium based browsers, that points more to NVDA than anything else.

> Have you always had this issue, or did it start after an update to NVDA, Windows, or something else?

On this, I have no idea.  I reported the issue the first time I encountered it.

**Comment by Adriani90** [comment]
I cannot reproduce this with NVDA 2023.3 or nvda last alpha version and Vivaldi 6.4.3160.47 x64.
It seems this is fixed in Vivaldi 6.4.3160.47 64bit. NVDA reports the tab title correctly, followed by "section". I tested with 5 tabs open and traversing them with left and right arrow key.
Closing as works for me. If you are still having this issue in Vivaldi 6.4.x or newer, please comment and we can reopen.

**Comment by britechguy** [comment]
Sorry, but it's still occurring using NVDA 2023.3 and Vivaldi 6.4.3160.47 (Stable channel) (64-bit).

I have run the COM Registration Fixing Tool, Restarted my computer, and tried NVDA with Add-Ons disabled before posting this comment.

All I'm doing is hitting F6, to throw focus to the browser tabs area, and what's announced is only, "Clickable."  If I arrow about to traverse tabs once focus is there, it's just a chorus of "Clickable, clickable, clickable."

I'm happy to do a run with debug logging if someone wants it.

**Comment by britechguy** [comment]
I am happy to try with the latest alpha build if I can do so using it as a portable.  But I also need the link to where that is acquired, as I don't normally deal with alpha builds except upon request.

But since the statement was made that it could not be reproduced with NVDA 2023.3 and the latest version of Vivaldi (6.4.3160.47) I just went with 2023.3 for testing here.

**Comment by Adriani90** [comment]
@britechguy could you please reinstall Vivaldi and NVDA and report the result? I am definitely not able to reproduce this in earlier versions of NVDA. aFter you press f6 to land on the tabs area, do you switch to focus mode with nvda+space bar and then use the arrow keys? Are is this in browse mode?
If this behavior is in browse mode, then it is not related to NVDA, but to the presentation of elements in the DOM which is handled by Vivaldi. If they put clickable on every empty line or button, then NVDA will report this. What if you turn off reporting of "clickable" in NVDA document formating settings?

**Comment by Nael-Sayegh** [comment]
Hello,
Please try with the latest alpha version of NVDA available at this address and give us your feedback:
https://www.nvaccess.org/files/nvda/snapshots/alpha/nvda_snapshot_alpha-30154,021c13da.exe
Thank

**Comment by XLTechie** [comment]
@britechguy, have you tried clearing the Vivaldi cache?

I do strongly suggest you test both Vivaldi and Brave with Narrator, as this has 
all the indicators of being a Vivaldi issue. Odd that it would be on two 
machines though.

Also, this: 
https://help.vivaldi.com/desktop/troubleshoot/troubleshooting-issues/

You may want to try disabling extensions, or testing in another profile.

**Comment by britechguy** [comment]
Clearing cache had no effect.  I won't get to anything else until sometime over the weekend, but will report back.
