### ISSUE TITLE
Speech stops in Windows 7 systems since nvda 2011.1

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#1710]
**Reported by briang1 on 2011-08-07 19:33**
## I'm creating this ticket as a place holder and somewhere to put current info about this problem. Note: I myself cannot  regularly access a win 7 machine.

From Davy Cuppens davy.cuppens@skynet.be
Hey devs

Here I have a log in which I will give one comment: you will sometimes find 
the phrase toegang geweigerd in Dutch, this means access denied or refused!
I hope I can help the devs resolving this annoying issue!

It is a log after the speech went away and NVDA is still following braille 
but is very sluggisch then en difficult to handle.

Log file hopefully attached

This file is a compendium of posts to the freelist group pertaining to  crashing, exiting or stopping speaking of nvda in Windows 7  since the launch of 2011.1 to the present date of 7th Aug 2011

Attribution where possible.

From: "Davy Cuppens" davy.cuppens@skynet.be

Subject: [NVDA losing speech and very unstable since 2011.1.1
Date: Mon, 18 Jul 2011 23:31:32 +0200

Hey folks

Now I have tested thoroughly. NVDA has become unstable in win 7 64 bit 
systems.
On very regular bases you lose speech whatever synths you use. It is even 
not possible to turn nvda off with nvda key and q. Sometimes alt tabbing 
brings up the nvda menu to close it down but the only thing you have is 
braille. I have not made any changes or installed new programs or components 
to my system. The only thing that I could think about is that things changed 
after sp1 of win7 was installed. I use other screenreaders as well and to 
make sure that they are not conflicting I have even shutdown remaining 
processes after the loading of nvda, f.e. weli64.exe which is a Windoweyes 
component after testing this screenreader.
I use Avast on my system but even when disabling all virus scanning 
processes the problem keeps going.
Now when using other screen readers, they run smooth as before so that I 
must conclude that the latest Nvda code is unstable for win7 64 bit systems.
Sometimes I notice that the first, let say 20 minutes of NVDA usage the 
program remains very stable and keeps on running with speech and braille 
output but after this, very often speech is silenced when doing some tasks 
so that NVDA has to be restarted.
It is not easy to report a reproducable information because it happens in 
all possible cases, browsing the web, scrolling through folders etc ...
Greetz
Davy 

---

From: "Dave Mack" dcmack2@comcast.net

Subject: [nvda](nvda]) Re: NVDA losing speech and very unstable since 2011.1.1
Date: Mon, 18 Jul 2011 14:53:05 -0700

I have been hesitant to comment but as a low-vision 32-bit user of NVDA - 
who alternates between keyboard usage and a physical mouse - I, too, have 
experienced more frequent stability difficulties regarding long speech 
recovery delays, often neccessitating NVDA restarts to solve the problem in 
recent NVDA versions and snapshots.  Since debug does not track mouse-usage 
I am not able to provide the devs with a log of the problem which I notice 
most often with mouse movements but I suspect it has something to do with 
how the video is captured and reported and processed as quick cursor changes 
are made between various windows and formats.  Just a wild guess and wonder 
if others have similar experiences.

Grandpa Dave in California
P.S. - I am also using Win 7 but 32-bit here and have the speech drop 
problem with all synths after 15 or 20 minutes, sometimes much less.

---

From: shaun everiss sm.everiss@gmail.com

Subject: [Re: NVDA losing speech and very unstable since 2011.1.1
Date: Tue, 19 Jul 2011 12:35:22 +1200

this happens with 2011.1.1 on win7 32 bit ocationally.
Sometimes when accessing large folders of files nvda will either lock 
or plain crash and quit on me.
Its annoying really.

---

From: Bates100 bates100@btconnect.com

Subject: [nvda](nvda]) Re: [SPAM](!!)  Re: NVDA losing speech and very unstable since
 2011.1.1

Date: Tue, 19 Jul 2011 09:47:17 +0100

I am relieved to hear others are having provlems with NVDA losing 
speech.   I am using Win 7 32bit,  and since June NVDA has been stopping 
occasionally, initially for 10 to 20 seconds before resuming,  but I now 
sometimes have to restart with con+alt+N.

I have not downloaded any snapshots or updates, and at first wondered if 
this was caused by too fast keystroking or perhaps extra loading whilst 
Kasperski was updating in the background  But at least I am now 
reassured that I have not picked up any malware!
I do not know how to check if I have Win7 SP1 installed, and await any 
helpful advice.
David Bates

---

From: "Davy Cuppens" davy.cuppens@skynet.be

Subject: [Re: NVDA losing speech and very unstable since 2011.1.1
Date: Tue, 19 Jul 2011 14:55:32 +0200

I can reproduce this, in fact I have up to 1200 mp3 files in my my music 
folder and very often while browsing them the problem occurs! This is really 
a NVDA problem because behaviour with other screenreaders has not altered 
these days!
Regards
Davy

---

From: Kevin Cussick the.big.white.shepherd@googlemail.com

Subject: [nvda](nvda]) Re: NVDA losing speech and very unstable since 2011.1.1

Date: Tue, 19 Jul 2011 18:58:23 +0100

forgot to say sorry this will have to be quick. I am running 32 bit 
## window's7 and this happens as well.

From

> Grandpa Dave in California

Subject: [Re: NVDA losing speech and very unstable since
  2011.1.1

no say I am viewing a mp3 folder, or large directory, well some times 
after scroling down at reasonable fast speed the program will quit.

> When scrolling down a long list of files with Windows Explorer in Win 7
> 
> using keyboard I am not able to replicate the problem so far. It would
> 
> be good to know, however, what View settings people are using. Is the
> 
> View set to List only or Details? Thanks.

The last email was missing from my system so took it from the quoted  section of the following email.

---

From: Kevin Cussick the.big.white.shepherd@googlemail.com

Date: Wed, 20 Jul 2011 19:02:33 +0100
Subject: [nvda](nvda]) Re: NVDA losing speech and very unstable since  2011.1.1

I have to keep this breef I use espeak and have this problem more often 
with thunder bird but with other things like maybe going threw my drop 
box folder.

I have my view  set to list. I have other sinths but I use only espeak 
really. except on the log on screen I use pieco.

---

From: Bates100 bates100@btconnect.com

Date: Wed, 03 Aug 2011 11:04:16 +0100

Subject: [Re: Windows 7 speech stopping  issues

I experienced this issue with Win 7-32  and NVDA 2011.1.1, but since 
changing from XP I found that I tended to leave more programmes open at 
the same time.  Since reading comments from the list  I now keep fewer 
programmes open and this problem seems to have gone away"

David Bates

---

From: "Dave Mack" dcmack2@comcast.net

Subject: [nvda](nvda]) Re: NVDA nolonger compatible with wing7!
Date: Sat, 6 Aug 2011 08:55:55 -0700

Brian, I have tried in vain to figure out why NVDA often needs to be 
restarted in Win 7 as I am unable to duplicate the events as it almost seems 
to happen randomly - sometimes when using keyboard and sometimes with a 
mouse on both eSpeak and other synths.  In the mouse scenario it almost 
seems that NVDA is trying to read to much info as the mouse arrow passes 
over a lot of different text types when traversing from one part of the 
screen to another, say from a text field to a menu button or other 
programmatic text of some kind.  It may be related to the  video hooking or 
whatever.  In the case of keyboard usage, for me NVDA seems to most 
frequently stop voicing when arrowing up or down a list of some kind - like 
a list of emails, list of files, or list of word occurrences in a program 
such as Amazon's Kindle app for PC.  But, again, this sometimes works fine 
and sometimes seems like some kind of delay occurs and NVDA either resumes 
after about ten or fifteen seconds or does not resume at all.
Could it be some kind of a buffer related issue as I notice that NVDA is 
still reporting things after I have moved the cursor somewhere else and I 
sometimes restart NVDA just to shut it up and start responding accurately. 
Anyway, for me, however, the problem does not happen frequently enough to be 
a major problem yet and is more of a minor nuisance periodically.

Grandpa Dave in California

---

Note i have left out repitition or muddled comments that do not really help. 
 Two things strike me. Lots of things changing, ie scrolling up and down, and maybe more processor usage by other software, so it might not be wholly nvda, but more the way processor cores are used by it under certain conditions.

This is of course conjecture

**Comment by ehollig** [comment]
Is this still the case with Windows 7 systems? I would like to say and hope not.

**Comment by fernando-jose-silva** [comment]
Unfortunately I still have this problem on a machine with nvda currently master 14172 and windows 7 64bits.
The nvda stops responding for about 15 seconds and then resumes working correctly.
These crashes occur several times a day and occur at various locations, reading web pages, reading emails, browsing folders.
I am available.

**Comment by leonardder** [comment]
cc @brian1gaff

**Comment by bhavyashah** [comment]
@leonardder Since this ticket is a duplicate of #3029, should this not be closed? It seems that @fernando-jose-silva seems to be able to reproduce the described behaviour, implying that this issue is still existent. Could we please have some help in troubleshooting and triaging this issue? @feerrenrut @jcsteh

**Comment by fernando-jose-silva** [comment]
Yes, thank you.

Enviado do meu iPhone

**Comment by feerrenrut** [comment]
@fernando-jose-silva Could you please upload an NVDA log (with debug level logging) after this next occurs on your machine? The logs we have are all quite old, and I am worried that they may mislead us.

**Comment by bhavyashah** [comment]
This is just a gentle ping for @fernando-jose-silva to keep https://github.com/nvaccess/nvda/issues/1710#issuecomment-320580647 in mind and send across a log when the reported issue next occurs.

**Comment by fernando-jose-silva** [comment]
Hello everyone.
Sorry for the delay.
I made some discoveries that solved my problem that I will report below, however I would like to point out that I am not sure that this will solve the other errors reported in this same call.
I accidentally decided for a while to disable all of the beeping sounds of nvda like:
Line indentation announcements (sounds).
And some addons that emitted beeps like:
Object tones
E Report paragraphs
And the locking problems did not matter anymore.
Which led me to believe that the sound driver of this machine can not efficiently reproduce the nvda synthesizer and beeping sounds.
I have already used other machines with windows 7, and I use other machines with windows 10 and this problem did not happen, which leads me to believe that it is the sound driver of this machine.
Just for reference the driver is:
Headphones; High Definition Audio Device; Default Device 2 of 2
The computer is a Lenovo notebook, and the problem occurs using the headset, so this driver.
Thank you all.
I can not try to update this driver, this is a working machine and I am not an administrator.

**Comment by ehollig** [comment]
@fernando-jose-silva, it sounds from https://github.com/nvaccess/nvda/issues/1710#issuecomment-322036706 that this issue is resolved from you. Is this the case, and if so, I think this issue can be closed as we have not had any reports of this for several years.

**Comment by fernando-jose-silva** [comment]
Actually I still have this problem.
If I have any kind of nvda beeps enabled these crashes in the nvda speech occur.
In order for me to not try these locks, I need to disable all nvda beeps, such as on breadcrumbs, line indentation, and any locations with beeping options.

This only occurs on windows 7, on windows 10 on two other machines that use this does not occur.

**Comment by Adriani90** [comment]
Can anyone still reproduce this? I am not able to reproduce it.

Moreover, the lags can have thousands of reasons. As far as I can read from the e-mails of the original author, his issue was solved when he did not open many programs at the same time. I guess this could be related to com and get focus issue and thus, might be related to following issues:

#8389 and
#7982.

**Comment by ehollig** [comment]
Closing as worksforme. Thank you @Adriani90 for  the testing. You may be right, in this may be related to other issues. Thus, closing
