### ISSUE TITLE
When changing between SAPI 5 voices the selected voice rate is lost and reset to 50.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2320]
**Reported by heikofolkerts on 2012-05-10 19:31**
Changing the SAPI voice e.g. when switching to another language or just another voice through the settings dialog looses the selected voice rate.
Steps to recreate:
1. Select a SAPI 5 voice and set the voice rate to e.g. 70.
2. Select another voice through the voice settings dialog - leave the rate as it is.
3. The new voice is used but in rate 50 which is OK since there is no rate set for the new voice.
4. Select the SAPI voice from 1. - again don't touch the rate.
5. The NVDA uses the voice from 1. but again with rate 50 - so one has to restore the previous selected rate.

Either there is one global voice rate for SAPI 5 or maybe all voices or better yet for each voice the rate is saved individually.

**Comment by ehollig** [comment]
This probably has to do with the same bug why OneCore voices change their rate back to 50% when changed, and it is required to change the speed in the control panel. Either way, does this need an external fix @jcsteh?

**Comment by Adriani90** [comment]
@heikofolkerts is this still an issue for you?

**Comment by Adriani90** [comment]
I guess this will be partly solved in #8934.

**Comment by Adriani90** [comment]
@feerrenrut I guess this issue is solved after the PR referenced above was merged. Is this correct?

**Comment by lukaszgo1** [comment]
Still reproducible with NVDA version alpha-21035,37c7a29b
The voice parameters are reset not only when changing voices but also when pressing NVDA+Ctrl+down arrow in the synth settings ring and the selected voice is the last one.

**Comment by Adriani90** [comment]
@lukaszgo1 are you still seeing this issue in NVDA last alpha with WASAPI enabled?

**Comment by lukaszgo1** [comment]
Yes, this is still reproducible with NVDA alpha-29844,f14d344f

**Comment by Adriani90** [comment]
@k_kolev1985 are you still seeing this issue with NVDA last alpha? Now SAPI 5 is using WASAPI, this might have had a positive effect on the issue.

**Comment by k-kolev1985** [comment]
@Adriani90 Yes, the issue still persists. 
- With SAPI5 selected, I invoke the "Speech" section of the NVDA Settings dialog. 
- I change the speed of the currently selected SAPI5 to a value different than 50%. 
- I select a different SAPI5 voice. The voice speed of the newly selected voice is automatically set to 50%. 
- I select the previous SAPI5 voice. Its speed is automatically set to 50%, no matter the previously set by me speed. 
Test environment:
- Operating system: Windows 11 Pro version 24H2 (build 26100.2894), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- NVDA version: alpha-35024,19296bf4 (2025.1.0.35024).

**Comment by SaschaCowley** [comment]
Also an issue with SAPI4. Does not seem to affect eSpeak or OneCore
