### ISSUE TITLE
first-line css selector font information not reported

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#2919]
**Reported by advck1123 on 2013-01-09 08:36**
Hi. I'am using nvda with firefox nightly
first-line css selector font information is strange. The code is file attached.
1. open the file nightly.
2. Press nvda_f in first sentence.
Sorry for poor english. or Sorry. i'm not good at english.

**Comment by Adriani90** [comment]
@jcsteh I cannot reproduce this in Firefox 63.0.3. I guess the bug reported by you some years ago has been solved. Right?

**Comment by jcsteh** [comment]
No; the bug still exists and I can still reproduce it. See the referenced Mozilla bug for clearer steps to reproduce. It's pretty low priority, though.
