### ISSUE TITLE
Dynamic ARIA Tooltips aren't being announced when aria-describedby points to new tooltip ID refs on the same element

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4047]
**Reported by bgaraventa on 2014-04-03 17:15**
An ARIA Tooltip is formed when aria-describedby is set on the focusable element, which then points to the ID of an element that includes role="tooltip".

When new tooltips are rendered, and aria-describedby is dynamically changed to point to the new tooltip when the same element has focus, the new tooltip should automatically be announced.

The announced text should reflect the same value as accDescription in the accessibility tree, which is correctly updated in IE10 and in Firefox.

Steps to reproduce:
1. Visit
http://whatsock.com/test/dt_demo/Coding%20Arena/Inline%20Form%20Field%20Validation%20and%20Dynamic%20Help%20Tooltips/Dynamic%20Help%20Tooltip/demo.htm
2. Type "f", and confirm that the wrong tooltip text is announced.
3. Continue typing up to 5 characters in length, and confirm the correct tooltip text is never announced.

**Comment by ehollig** [comment]
As @jcsteh said in https://github.com/nvaccessAuto, [MozillaBug:991969](https://bugzilla.mozilla.org/show_bug.cgi?id=991969) was fixed for Firefox 31. Google Issue [Chromium:359857](https://bugs.chromium.org/p/chromium/issues/detail?id=359857) was fixed in January 2015. I believe this issue still exists in IE 11.

**Comment by ehollig** [comment]
As stated in https://github.com/nvaccess/nvda/issues/4047#issuecomment-317799317, this issue has been resolved for Chrome and Firefox. Testing in Internet Explorer and Edge still exhibits this behavior as described in https://github.com/nvaccess/nvda/issues/4047#issue-116040605.

**Comment by Adriani90** [comment]
This still exists in IE11 and Edge. @feerrenrut is this something for Webfix project?

**Comment by Adriani90** [comment]
In Edge Chromium 81 this works as expected. So only IE is affected by this issue still.

**Comment by Adriani90** [comment]
Support for IE ended completely in 2022 and is automatically removed from machines that still have it after an Edge update in february 2023. I am closing this as abandoned since I don't expect any further accessibility updates to IE or to IE mode in Edge.
