### ISSUE TITLE
aria-expanded change not reported in Chrome on a particular page

### ISSUE THREAD

**Issue by jcsteh** [nvaccess/nvda#6123]
Originally reported via private email:

> We are constructing a dropdown list/menu for our website, which can be seen toward the bottom of the page here:
> 
> https://support.office.com/en-us/article/Contact-Office-365-for-business-support-Admin-Help-32a17ca7-6fa0-4870-8a8d-e25ba4ccfd4b?ui=en-US&rs=en-US&ad=US
> 
> If you use NVDA on the dropdown in IE or Firefox, it exhibits a reasonable behavior on it (including saying “expanded” and “collapsed” when I open/close it).
> However, on Chrome, the dropdown does not say “expanded” and “collapsed” when I open and close it with Enter, even though the aria-expanded attribute toggles between true and false.
> Here’s the kicker: If the number of options in the dropdown is 4 or fewer, then it works fine! When I manually remove all the other options in the dropdown, the accessibility feature works!
> I’ve tried seeing whether it’s about the height of the options, but it doesn’t seem to affect the behavior.

This works intermittently for me. Sometimes, pressing enter reports the state change; other times, it doesn't. Some brief investigation with AccProbe suggests Chrome is firing a stateChange event as it should. For some reason, this doesn't seem to be reported by NVDA.

**Comment by leonardder** [comment]
@JCSTeh: Any info about the status of this?

**Comment by jcsteh** [comment]
No idea. P3 to investigate.

**Comment by Adriani90** [comment]
This issue is still reproducible in Chrome 71. The status expanded or colapsed is not announced on the button submenu. In other browsers it works properly. Could it also be a bug in Chrome?
cc: @derekriemer

**Comment by AdeyemiA** [comment]
@Adriani90 one work-around is to add role="menuitem"; this should fix it. See [here](https://github.com/w3c/aria/issues/454#issuecomment-308305351).

**Comment by Adriani90** [comment]
This issue is not reproducible anymore in NVDA alpha-18064,e579eb02 and Chrome 75.0.3770.142. Now NVDA reports properly colapsed and expanded when pressing enter on the submenu buttons and also announces their status when using arrow keys in browse mode to navigate.
I am closing this as works for me. Please comment on it if it is still reproducible for you and we can reopen the discussion. Thanks.

**Comment by snpatel2263** [comment]
Hello,
I am using NVDA 2020.4 and Chrome 97.0.4692.99 and this issue is still reproducible.
However It is working in mozila and safari as well and chrome in Apple. only thing where I can reproduce is chrome+windows+nvda and chrome+windows+jaws.
Is there a solution or It behaves like that??
