### ISSUE TITLE
IntelliJ2016.2: focus is not jumping to cod editor after selecting a value in autocompletion list.

### ISSUE THREAD

**Issue by beqabeqa473** [nvaccess/nvda#6224]
hello.

in IntelliJ2016.2 focus is not jumping to cod editor after selecting a value from autocompletion list.

is it something to be done in nvda?

**Comment by mohammad-suliman** [comment]
don't know how much Intellij idea is updated with latest android studio accessibility improvements. This was a major problem which have been fixed by Google in android studio 2.2 update.
if this version of idea has the latest accessibility code, follow these steps quoted from android studio accessibility doc to get auto completion to work with screen readers:
"
* Android Studio must be configured to support screen readers
* Open the "Settings" dialog via the "File > Settings" menu item
◾* Go the "Appearance & Behavior > System Settings" entry
* Ensure the "Support screen readers" checkbox is checked
* Click "Ok"
* Restart Android Studio

Note: If the "Support screen readers" option is not checked, Android Studio may still partially work with screen readers, but enabling the option vastly improves keyboard navigation (e.g TAB/Shift-TAB keys) as well as the way focus interacts with complex features such as Code Completion and Text popups.
"
link to the doc:
[configuring accessibility on windows](http://tools.android.com/tech-docs/accessibility/configuring-accessibility-on-windows)

you can ask Intellij devs to sync the code with android studio code, so, this  works as expected.

**Comment by jmh-aira** [comment]
In INteliJ 2017.1, (latest version as of today.) the focus is still not placed after using autocomplete.  THis is still the case with android studio 2.4 preview builds.  Any ideas on how this can be fixed?

**Comment by Adriani90** [comment]
@beqabeqa473, @jmh-aira are you still having this issue in last NVDA version and last IntelliJ version?

**Comment by clementb49** [comment]
Hi,
If you enable the aforementioned screen reader support, this problem is not present anymore (in the last version of NVDA and IntelliJ based IDE). 
I think we can close this issue.

**Comment by Brian1Gaff** [comment]
Is this in the manual?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by Adriani90** [comment]
Closing as works for me
