### ISSUE TITLE
Always read superscripted and subscripted numbers.

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6438]
one thing that might be useful is to ignore the font attribute setting for numbers, (or create a new one for subscript/superscript) so that NVDA will read numbers like 10^44 as 10 superscript 44, rather than 1044. it's annoying to have to turn all font attributes on for a webpage, just so that I can hear 10 superscript 44.
This might require a redesign of the font settings of the document formatting dialog, maybe a configure font settings button in this dialog, so users can have more fine grained control over the font.

**Comment by jcsteh** [comment]
I think separating superscript/subscript from attributes makes sense. I'd be reluctant (at least at this stage) to introduce heuristics based on the presence of numbers or the like, as this doesn't account for some edge cases (e.g. x sub y) and it's hard to get right. It's worth noting, though, that you would hear "10 superscript 44 baseline".

P3 because this would certainly improve some common use cases and it's not a difficult change.

**Comment by Adriani90** [comment]
cc: @nvdaes

**Comment by DrSooom** [comment]
Based on [this comment in PR #10448](https://github.com/nvaccess/nvda/pull/10448#issuecomment-552017369) I suggest to extent this issue here to the most important font attributes. Here the list:
+ Bold
+ Italic
+ Underlined
+ Double underlined
+ Strikethrough
+ Superscript
+ Subscript
+ Small caps
+ Others

**Comment by Adriani90** [comment]
cc: @lukaszgo1

**Comment by feerrenrut** [comment]
I think this issue has been resolved with PR #10919. Always reading super / sub script can now be configured independently of other format settings.

**Comment by Adriani90** [comment]
I think this is not fixed, but this might be due to the rendering of the characters. If I write 1^3 NVDA still reads "1 3" instead of "1 superscript 3".

**Comment by Adriani90** [comment]
Actually such numbers are usually read as for example 1 to the 3 instead of "1 subscript 3".

**Comment by feerrenrut** [comment]
@Adriani90 I think the `^` character was just used to denote that the following number would be formatted as superscript. I think this because Derek says in the initial description: 
>it's annoying to have to turn all font attributes on for a webpage

Indicating that it is already something that can be enabled, but only if you enable other format reporting that isn't desired.

**Comment by derekriemer** [comment]
yes. For example, science fields use super/subscripts. For example, `<sup>2</sup>C` would be two carbon atoms in chemical notation, and that should not be pronounced with power notation. another example is an equation like the following. a<sub>1</sub>+a<sub>2</sub>+...+a<sub>n</sub> = b
This equation would generally be read as a sub 1 plus a sub two plus ...

**Comment by CyrilleB79** [comment]
Given the initial description and the last comments, I'll close this issue as fixed by #10919.

If you still need a finer control of reported attributes, please open a new issue or comment in existing ones.
