### ISSUE TITLE
multiple issues with NVDA and spotify.

### ISSUE THREAD

**Issue by devil418** [nvaccess/nvda#6679]
NVDA works improperly with spotify desktop in the following ways.
1.. When pressing enter on some items (i.e. playlists or context menu items  they're not activated. Instead, It's needed to route the mouse to that particular item (nvda+/) and click it with /.
2. When opening a context menu on an item, nvda doesn't automatically jump to it. Instead, we have to do it manually.
3. When in the menu bar, the state of some items (i.e. shuffle or repeat) is not announced. 
4. When toggling shuffle with ctrl+s, nvda doesn't say anything. 
5. "clickable" is announced multiple times in a lot of places (i.e. "clickable link clickable albums"). It happens very often when being in the last section of the app.

**Comment by josephsl** [comment]
Hi, did you contact Spotify developers about these issues first? If not, I recommend doing so. Thanks.

**Comment by miki123211** [comment]
I didn't.
If that's the recommended way of resolving this, I will.W dniu 
2016-12-25 o 18:28, Joseph Lee pisze:

**Comment by josephsl** [comment]
Hi, try contacting app developers, because they need to be aware of these and other accessibility issues. If they are unwilling to work with you, then call us (NVDA developers) so one of us can send a letter to Spotify and offer a partnership in resolving this from developer’s perspective. Thanks.

**Comment by ehollig** [comment]
It sounds like 1, 3, and 5 are resolved for this issue due to an update with the desktop version of Spotify. @devil418 do you have any additional updates?

**Comment by Adriani90** [comment]
@devil418 are you still available to respond to @ehollig's comment above? Thanks.

**Comment by devil418** [comment]
3 is definitely fixed, not sure about 5, as I just have clickable off. 1 is still a problem, and there are more issues now, particularly with not reading items in long lists (playlsts etc).

**Comment by Adriani90** [comment]
@devil418 the app has become much more accessible since last update. Clickable is still reported but this is not reported multiple times since this was fixed in an earlier NVDA version.
I am closing this issue as works for me. If you have further issues with the app, please open new issues for each of them. Thanks.
