### ISSUE TITLE
NVDA says "edge of table" on CapitalOne transactions view

### ISSUE THREAD

**Issue by munawarb** [nvaccess/nvda#6793]
On the CapitalOne website, when I click "Transactions," there is a table that shows up with all my transactions. Pressing any of the NVDA table navigation keys such as CTRL+ALT+DOWN ARROW inside this table reports "edge of table." I think this is an Aria Grid control.

**Comment by munawarb** [comment]
@Adriani90 Firefox Quantum.

**Comment by Adriani90** [comment]
cc: @jcsteh this could be similar to the behavior on the gmail website.

**Comment by jcsteh** [comment]
> cc: @jcsteh this could be similar to the behavior on the gmail website.

What behaviour on Gmail exactly?

**Comment by Adriani90** [comment]
Ok just ignore my last comment, the behavior in GMail where table navigation didn't work is solved in Firefox 66.0.2. @munawarb could you please test with Firefox 66.0.2 and NVDA 2019.1 if the transaction table works now? Thanks!

**Comment by munawarb** [comment]
Hi @Adriani90, I still get the problem for the Capital One website. I tried to look at the HTML but it seems like they're running a web application and their page is rendered completely using JavaScript, so I couldn't poke around at the the raw HTML.

I noticed that NVDA is saying "table with 1 row and 0 columns" and, while it's announcing "header cell" for the different cells, it's as if the cells are floating and are completely outside the table. NVDA does say "end of table" though once I'm past the transactions view. It's odd because they do seem to have labeled table headers properly and are also using headings as indicators, but there's something really wrong with the table itself that I sadly can't see because it's buried in the JavaScript files somewhere.

So I'm not sure if this layout is simply too complex for NVDA to handle or if there's something else wrong. I might be able to securely deliver the Capital One transactions view to you somehow.

**Comment by Adriani90** [comment]
@munawarb did you report this issue also to them? Maybe the table is not exposed correctly due to web authoring issues.

**Comment by Adriani90** [comment]
@munawarb I think there was a kind of related PR which tackled such tables, at least I had a similar problem with SAP web based tools. In my case this is fixed now. Can you test if you still have this problem with NVDA 2022.4 or NVDA 2023.1 Beta?

**Comment by munawarb** [comment]
@Adriani90 Yes, this is fixed now. I can use table navigation keys just fine in the transactions view. I just now tested it with 2022.3.3

**Comment by Adriani90** [comment]
Thanks for the update. Closing as works for me.
