### ISSUE TITLE
NVDA does not shift to focus mode on menu buttons that have an aria-hasPopup attribute

### ISSUE THREAD

**Issue by arodenbeck** [nvaccess/nvda#7836]
When a menu button uses the aria-haspopup attribute, NVDA will announce that the menu is expanded, but does not shift into focus mode for navigation. Hitting down arrow will focus the first item in the menu, but subsequent presses of down arrow simply navigate the DOM in browse mode. 
If these menu buttons are between <form> tags, NVDA seems to properly navigate the menus, unless one manually toggles browse mode. At this point NVDA acts as described above.
This behavior was observed in the latest version of Chrome, as well as Firefox 52, 56, and Quantum.

Windows: Version	10.0.16299 Build 16299
NVDA: Next-14675,14728b95

**Comment by PratikP1** [comment]
I can generally confirm this behavior. It would be good to have either a live example or code in this issue for reference.

**Comment by arodenbeck** [comment]
Thanks for the feedback. Where I encounter this the most is behind a login. I will try to find a good example, and update the issue.

**Comment by Adriani90** [comment]
I can confirm this, try for example buttons in google forms or google tables, docs etc.

**Comment by Adriani90** [comment]
However, there are some cases when NVDA does change to focus mode, namely when the pop up atribute is atributed to a link and not to a button (i.e. MS Share Point)

**Comment by Adriani90** [comment]
Another very good example is www.facebook.com

**Comment by bhavyashah** [comment]
Confirmed. The steps to reproduce this issue with NVDA 2017.4 and Chrome 63.0 stable on a Windows 8.1 system are as follows:
* Ensure that you have signed into a Google account.
* Visit https://drive.google.com/drive/my-drive.
* Locate the control just preceding the Folders and views heading which NVDA reads as "menu button  collapsed  subMenu Settings".
* Use various techniques to interact with the items contained by this menu button.
Expected Result: Pressing Enter, Spacebar, Alt+down arrow, left mouse click or NVDA+Space should all take the user into the items contained by the menu button.
Actual Result: Pressing Enter, Spacebar or performing a left mouse click after moving the mouse pointer to the current navigator object simply collapses and expands the submenu, but any subsequent arrowing in either direction does not actually take the user into it but continues to traverse through the main document. Pressing NVDA+Space toggles to focus mode, after which arrowing traverses through the items contained by the submenu. Pressing Alt+down arrow directly focuses the first item of the menu button.
I think this needs to be tested with Firefox as well, since the results seem to be different in that case. I will be unable to do this because I use Firefox ESR instead of the latest stable version and since Firefox hangs terribly when I load any heavy webpage such as Drive. Having said that, this ticket ought to be given a fairly high priority because it makes web interaction with these increasingly common menu buttons very confusing and unintuitive. As a user, I would expect, above anything else, Enter and Spacebar to both always get me into the contents of such controls.

**Comment by feerrenrut** [comment]
I think the next step here is to build a minimal example that reproduces the issue. This will make it much easier to confirm the problem, and be sure we have fixed it. External websites are a moving target, especially if they are often updated.

**Comment by Adriani90** [comment]
This works now as expected in all examples provided in this issue. I have tested with NVDA 2019.1.1 and Firefox 66.0.3 as well as Chrome 74.
Sometimes you have to press multiple times enter on a button with submenu to expand it but this is another issue.
Closing as works for me.

**Comment by arodenbeck** [comment]
@Adriani90 I tested this as well with NVDA 2019.1.1 and am still seeing the issue. I have more information about what is causing the problem now, and have created a Salesforce login to demonstrate the issue.
The problem seems to be with menus which only expand, and do not focus the first menu item. The example from Google had one menu which focused the first item, and one that did not. On the version which did not focus the first item, NVDA will expand the menu, but since it does not switch to focus mode, down arrow is still not moving through the menu items.

Steps to reproduce:
Navigate to http://login.salesforce.com
Username: user@a11ytester.org.github
Password: Test1234!
Once logged in, Press CTRL+Home to ensure you are at the top of the page
Tab to the "Skip to navigation" skip link and press enter
Tab to Home, Accounts, and finally Accounts menu
Press enter on the Accounts menu button
Notice that focus mode does not activate
Press down arrow and observe that the first option, "New Account" is indeed present, even though NVDA did not change modes, or announce that the menu was expanded
Press down arrow again, and observe that NVDA continues down the page, rather than passing the down arrow keystroke to the application

I have attempted to remove any problems with loggin in with this account. Please let me know if the password does not seem to work, or if you are locked out due to an unknown IP address.

**Comment by Adriani90** [comment]
@arodenbeck I am reopenning this issue. Thank you very much for this test case and for the elaboration. Now I can reproduce it but only in Google Chrome 74. In Firefox it seems to work as expected.
cc: @derekriemer

**Comment by jcsteh** [comment]
> The problem seems to be with menus which only expand, and do not focus the first menu item.

That is a website authoring error. The first item should be focused when the menu expands. NVDA only decides whether to switch between browse and focus modes when the focus moves. Since the focus doesn't move here, that decision does not occur.

**Comment by pr3tori4n** [comment]
I can confirm this is happening in `v2020.1`
A simple reproduction case would be to open NVDA and navigate to the example on this page.
https://www.w3.org/TR/wai-aria-practices-1.1/examples/menu-button/menu-button-actions.html
Here is an example from w3.org for how to create an accessible dropdown menu. One of the functional requirements is that pressing ArrowUp or ArrowDown while focus is on the button will open the menu and select either the first or last element, respectively. In order for this to work, NVDA would need to enter focus mode. I think there should be some aria attributes that when present on a `<button>` element, NVDA switches to focus mode. certain roles, such as `menu` or `aria-haspopop` make sense as these will likely have special keyboard events.

**Comment by Adriani90** [comment]
@pr3tori4n your example is not reproducible anymore. That works as expected with NVDA last alpha, Firefox and Chromium browsers 112.

Given the comment from Jamie above, this works as expected as long as the web author redirects the focus to the first menu item when expanding the button.

Closing as works for me.

If you are still having this issue, please comment with updated steps to reproduce and a valid test case and we can reopen.

**Comment by SergKozyrev** [comment]
Still have this issue with NVDA 2024.4.1.
A simple reproduction case would be to open NVDA and navigate to the example on this page.
https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/
Here is an example from w3.org for how to create an accessible dropdown menu. One of the functional requirements is that pressing ArrowUp or ArrowDown while focus is on the button will open the menu and select either the first or last element, respectively. In order for this to work, NVDA would need to enter focus mode. I think there should be some aria attributes that when present on a <button> element, NVDA switches to focus mode. certain roles, such as menu or aria-haspopop make sense as these will likely have special keyboard events.
