### ISSUE TITLE
NVDA reacts very slowly when moving between lines whilst reading emails in Outlook 2016

### ISSUE THREAD

**Issue by Ednunp** [nvaccess/nvda#8026]
when using any version of NVDA, Open an email message in Outlook 2016 by simply hitting enter. Reading character by character with the cursor keys is very responsive for the most part, but cursoring up and down between lines can give a delay of over a second on occasion and makes it very hard to scroll through an email. I assume this might be related to the object redrawing like so many of the 2016 MS products?

**Comment by mohdshara** [comment]
Agreed, issue is very noticeable for me too all the time with outlook 2016. 

not sure if this is related, but while composing a reply character echo is very slow. Does anyone notice this? Should I open a separate issue for this annoying bug?

**Comment by Adriani90** [comment]
I also notice some delay when navigating line by line in Outlook 2016 / 365. However, it is very strange that NVDA reacts much faster when using ctrl+arrow keys to navigate paragraph by paragraph or word by word.

**Comment by DGartmann** [comment]
With NVDA 2022.3 beta 2 this issue is still very much present. Using:
appModule.productName: 'Microsoft Outlook'
appModule.productVersion: '16.0.15427.20210'

**Comment by Adriani90** [comment]
Here is a test email which should properly reflect this sluggishness. The difference between either pressing arrow keys, or pressing ctrl+arrow key to navigate is significant.
I am testing with eSpeak on NVDA alpha-28179,345154a6 (2023.2.0.28179)


[Engagement Zeigen  der DSEE-Newsletter Mai 2023.zip](https://github.com/nvaccess/nvda/files/11409780/Engagement.Zeigen.der.DSEE-Newsletter.Mai.2023.zip)

**Comment by Adriani90** [comment]
There is no noticeable performance difference between arrow keys or ctrl+arrow keys when UIA for Microsoft Word is enabled. The performance when navigating with arrow keys is much better with UIA enabled.
cc: @michaelDCurran

**Comment by Adriani90** [comment]
Update with NVDA 2023.2 on Outlook 2016, without using UIA, the performance is way better. There is practically no difference between arrow keys and ctrl+arrow keys when navigating through the email. From my point of view this issue is fixed. @Ednunp, @DGartmann, @rperez030 can you confirm this works for you as well in NVDA 2023.2?

**Comment by CyrilleB79** [comment]
Outlook 16.0.16731.20170 and NVDA 2023.2:
The issue is still present. However, when restarting NVDA and Outlook, the performances improve. To summarize, the issue seems to become worse when NVDA and / or Outlook is running for a long time.

**Comment by Adriani90** [comment]
This is still reproducible especially when the list contains emails with large attachments, priority tags or events with attachments and priority tags.
It seems NVDA tries to retrieve additional information related to these tags and it is slow in doing this.
Is there any exprience with other screen readers such as Jaws or Narator? Is there a performance issue noticeable as well?

**Comment by CyrilleB79** [comment]
Just mentioning that, just today, Outlook e-mail reading being sluggish, especially in newsletters, has been reported on the French users mailing list. This sluggishness is being reported regularly, either with say all or when reading line by line.

This issue is a key difference with NVDA's main competitor (Jaws), preventing some people to use NVDA 100% of the time.

Cc @gerald-hartig for awareness.

**Comment by gerald-hartig** [comment]
Closing issue. Created https://github.com/nvaccess/nvda/issues/17337 to track this issue.
