### ISSUE TITLE
Impossible to install Speech History add-on in the latest alpha

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#9289]
### Steps to reproduce:
1. Download speech History add-on from https://addons.nvda-project.org/addons/speech_history.en.html 
2. Try to install it.
### Actual behavior:
The error sound is played and the following is written in the log
WARNING - addonHandler._report_manifest_errors (23:09:15.276):
Error loading manifest:
{'docFileName': True, 'description': VdtTypeError('the value "[u\'This add-on allows you to review the 100 most recent strings spoken by NVDA\', u\'by default using Shift+F11 and Shift+F12.  Additionally\', u\'you can copy any spoken item to the clipboard by pressing F12.\']" is of the wrong type.',), 'author': VdtTypeError('the value "[u\'Tyler Spivey\', u\'James Scholes\']" is of the wrong type.',), 'url': True, 'lastTestedNVDAVersion': True, 'summary': True, 'minimumNVDAVersion': True, 'version': True, 'name': True}
ERROR - gui.addonGui.installAddon (23:09:15.276):
Error opening addon bundle from C:\Users\Lukasz\AppData\Local\Temp\speechHistory.nvda-addon
Traceback (most recent call last):
  File "gui\addonGui.pyc", line 445, in installAddon
  File "addonHandler\__init__.pyc", line 564, in __init__
AddonError: Manifest file has errors.

### Expected behavior:
The add-on should install.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
NVDA version alpha-16781,4e899259

#### Windows version:
Windows 7
#### Name and version of other software in use when reproducing the issue:
Latest Speech History add-on
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
No, I haven't but I assume it is introduced by the add-on compatibility check. I would report it to the Speech History author, but we were assured, that for now add-on authors do not need to update their add--ons to stay compatible with 2019.1.

**Comment by lukaszgo1** [comment]
cc @feerrenrut

**Comment by leonardder** [comment]
This add-on manifest has its description spread over multiple lines, which might be problematic. It has no add-on compatibility values in its manifest, and therefore I do not yet know why it does not install while it did before.

cc @josephsl

**Comment by josephsl** [comment]
CC @TSpivey

**Comment by tspivey** [comment]
CC @jscholes

The manifest.ini uses unquoted strings, so the comma is taken as a list item separator. Whatever NVDA uses to validate now fails when given lists for the author and description.

Easy mistake to make, especially since the developer guide has no mention of this and itself uses unquoted strings.

**Comment by lukaszgo1** [comment]
Maybe then we shouldn't be validating anything except real compatibility values?

**Comment by leonardder** [comment]
I think validation is essential, however it should not include backwards compatibility issues.

**Comment by lukaszgo1** [comment]
Is this going to be addressed before 2019.1?

**Comment by josephsl** [comment]
Hi, hopefully addressed in the latest alpha build. Thanks.

**Comment by lukaszgo1** [comment]
Unfortunately still fails in NVDA version alpha-16885,2ed7dbae

**Comment by josephsl** [comment]
Hi, yep, in this case, this is something add-on authors will definitely need to look into. Thanks.

**Comment by leonardder** [comment]
I think that this is not something that should be fixed on NVDA's end, as it is strictly spoken a problem in the add-ons manifest file.

**Comment by jscholes** [comment]
Agree with @leonardder.  Haven't got around to fixing it yet but I'd be happy to accept a pull request :)

**Comment by lukaszgo1** [comment]
@josephsl @leonardder From the developer perspective it makes sense to say that it is an add-on problem and close it, But for an end user it is simply something which worked and then stopped without a good reason. Validating add-on name, authors and description gives nothing and as seen here might cause problems. Even if Speech History would be fixed we would never know if some other add-on isn't suffering from this, and as I said above there is no gain from validating these fields.

**Comment by Adriani90** [comment]
This seems to be solved now, cc: @nvdaes. Can someone also confirm it? If so, then we ca close it I guess.

**Comment by jscholes** [comment]
The add-on manifest is fixed and a new version has been released.  I'm happy for it to be closed.

**Comment by lukaszgo1** [comment]
While this particular add-on is fixed they maybe others with the same problem - I've explained it above. Even dev guide uses strings without quotes. There is a #8594 for this, but there was no activity on it for almost 8 months. In short at the minimum we should merge #8594 as soon as possible and ideally the fields other than compat values shoullnd't be validated.

**Comment by lukaszgo1** [comment]
I've experienced it with another add-on available at http://www.zlotowicz.pl/nvda/klawiszeschowka.nvda-addon Any chance of looking into it? I can fix it by removing validation from fields other than compatibility values however don't want to do that without approval of someone more experienced. cc @feerrenrut

**Comment by josephsl** [comment]
Hi, I’d say we should keep validating all fields regardless, especially now that Python 3 transition is close at hand and its tie for add-on authors to seriously think about compatibility state of their add-ons. Thanks.

**Comment by josephsl** [comment]
Hi,

And we are now in transition phase. Unfortunately Speech History add-on is not compatible.

Thanks.

**Comment by lukaszgo1** [comment]
Even if Speech History isn't compatible with latest master this has nothing to do with this issue. As master is now Python 3 manifests need to be updated anyway either by add-ons authors or users  themselves, so I am closing this. I still don't believe that validation of add-on name, author and description makes much sense.
