### ISSUE TITLE
Chrome announces table, row, cell elements when using CSS display: table 

### ISSUE THREAD

**Issue by hills001** [nvaccess/nvda#9760]
I was recently reviewing a website which makes extensive use of CSS 'display: table', 'display: table-row' and 'display: table-cell' properties for layout purposes. These elements are nested several times to create a grid layout structure.

I noticed using Chrome, that NVDA would announce these elements as, for example, 'Table, Row minus one, column one'.

I think this could be related to an issue described here: https://www.456bereastreet.com/archive/201110/using_displaytable_has_semantic_effects_in_some_screen_readers/ however, I was unable to reproduce with the example code used in this article.

I am unsure whether this is truly a bug or is intentional behaviour. I noticed adding a 'role=presentation' attribute to the elements seemed to stop Chrome from announcing the elements, though I am unsure whether this would be the recommended approach to dealing with the issue.

### Steps to reproduce:
Visit demo page: https://nvda-display-table-issue-9760.netlify.app/
Use keyboard tab key to navigate to 'Your name' field.

### Actual behavior:
Using Chrome, NVDA announces the elements created using 'display: table', 'display: table-row', 'display: table-cell'

### Expected behavior:
Using Firefox, Internet Explorer 11 or MS Edge browsers, these elements are not announced to the user.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2019.1.1
#### Windows version:
Windows 10
#### Name and version of other software in use when reproducing the issue:
Chrome 75.0.3770.90
Internet Explorer 11
MS Edge (40.15063.674.0)
Firefox 67.0.2
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by aleventhal** [comment]
We've had feedback from users that they wanted to be able to navigate layout tables as tables in their screen reader. I think Chrome has this right. 

We provide the table information and interface, but also the object attribute layout-guess: true so that the screen reader can make the best decision on what to do.

**Comment by aleventhal** [comment]
Here are all the more object attributes that might help NVDA make a decision:
- tag
- xml-roles
- display (mirrors CSS display)
- layout-guess

Both ChromeVox and JAWS want to be able to allow the user to take advantage of the grid pattern in a page, whether it's intended as a table or not. Therefore, we're not likely to change this in Chrome.

**Comment by hills001** [comment]
Hi, thanks for the response and good to know this was requested by users. I'll close this issue.

**Comment by aleventhal** [comment]
I still think NVDA might want to change a couple of things:
- Change/reduce announcements that say something is a table when it's a layout table. Somehow make it clear that table nav is available without saying "this is a table", which might be confusing
- When something is a layout table, it may be worth downplaying it even more depending on the table size, e.g. a 5 column, 1 row table that's also a tabstrip -- no need to even bother with table nav announcements there (although perhaps the keys could still work, idk).

**Comment by jnurthen** [comment]
Yeah - can we reopen this? If not I'll file a new issue

**Comment by hills001** [comment]
Thanks for the follow up, I’ve reopened the issue.

**Comment by Adriani90** [comment]
@hills001 could you please provide a minimal test case or a new link? The link in the description does not work anymore, the codepen is expired.

cc: @feerrenrut

**Comment by hills001** [comment]
@Adriani90 Hi, I've just updated the original post with a link to a new demo.

**Comment by Adriani90** [comment]
@hills001 I think I cannot reproduce this issue with NVDA last alpha version and Chrome 83. Can you confirm?
You can download the last alpha here:
https://www.nvaccess.org/files/nvda/snapshots/

**Comment by hills001** [comment]
Hi, @Adriani90, I've just installed the NVDA alpha from Friday 15 May 2020 and have updated Chrome to version 83 but can still reproduce the issue. I notice in NVDA Settings/Document Formatting I had the options ticked for Tables, Row/column Headers and Cell Coordinates. Unchecking these options did solve the issue, however, I would imagine regular tables would also no longer be announced. I also had 'Include layout tables' unchecked in Settings/Browse mode, and when using the arrow key to navigate in browse mode the tables are not announced, the issue only occurs when tabbing to the input fields (ie focus mode).

**Comment by sharathvuppla** [comment]
Hi 

Do we have any update on the ticket

we are encountering same issue on 
OS: Windows 10 20H2
Browser: Edge chromium( 86.0.622.51)
NVDA 2020.2

**Comment by JamesCatt** [comment]
I've encountered this and another problem where table navigation breaks on an actual `table` nested inside, similar to the issue described in #8462.

Demo and description are available here: https://jamescatt.ca/test/nvdatables/

Note that in the demo, only `display: table` is used, and there are no direct children that would correspond to a `table` as in the original example. Also note that the "table" announcement issue (i.e., the original issue in this thread) only happens when tabbing to a focusable element. It does not occur with regular browsing via up/down arrow keys.

I agree with @aleventhal that Chrome should communicate it as a layout table with the extra info, but perhaps NVDA can be a little more specific in terms of the scenarios where it will communicate this as a table to the user?

**Comment by leonardder** [comment]
I think this was mostly fixed by #12360.

**Comment by Adriani90** [comment]
The link in the description does not work anymore.
@hills001, @JamesCatt, @jnurthen, @sharathvuppla can you still reproduce this issue with NVDA 2023.1?

**Comment by jendemes** [comment]
Is occurring for me with the following:

- OS: Windows 10.0.19045
- Browser: Chrome 112.0.5615.121
- NVDA version: 2023.1.0.27913
- NVDA "Include layout tables" setting both checked and unchecked 

The page I'm finding it on is internal to my employer so I'm unable to share it.

**Comment by Adriani90** [comment]
Does the layout table contain an aria role=table?

**Comment by Adriani90** [comment]
We definitely need a minimal test case here. Could you ast your IT department if they can extract a minimal anonyme test case from that table?

**Comment by Adriani90** [comment]
Ok I managed to reproduce this with the example from @JamesCatt  above in Chrome and Edge 112. On the first table, NVDA reports "table with 0 rows and 0 columns".

**Comment by Adriani90** [comment]
I am closing as abandoned, all minimal test cases here do not work anymore and we are missing updates from the initial author since many years upon request. Please provide an updated minimal test case and we can reopen.
