### ISSUE TITLE
An error occurred while starting NVDA-beta-18013

### ISSUE THREAD

**Issue by dingpengyu** [nvaccess/nvda#9913]
There will be an error tone when starting the test of NVDA beta 18013
### Steps to reproduce:
First install NVDA beta 18013 and start
Then cut to Windows OneCore voice and eSpeak NG voice for testing
Finally, after switching two speech synthesizers to start twice, both reports an error.
Note:
I stopped all installed plugins during the test.
### Actual behavior:
Play an error tone after restarting
### Expected behavior:
Play an error tone after restarting
#### NVDA installed/portable/running from source:
install
#### NVDA version:
 NVDA-beta-18013
#### Windows version:
windows-1903-10.0.18362.175
#### Name and version of other software in use when reproducing the issue:
NVDA-beta-18013
#### Other information about your system:
no
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
The following is the test log:
[nvda- Windows OneCore 语音.log](https://github.com/nvaccess/nvda/files/3380415/nvda-.Windows.OneCore.log)
thank

**Comment by leonardder** [comment]
I'm reading the following in your log:

`ImportError: No module named eci_vc`

Could you please make sure that your configuration is clean by resetting it to factory defaults and test again?

**Comment by dingpengyu** [comment]
The issue has been resolved by restoring the default settings. thanks for reminding

**Comment by Brian1Gaff** [comment]
If you mess with  the voice settings in different synths though do funny 
things still occur on  thenewer snaps, ie threshold etc?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- O

**Comment by leonardder** [comment]
Issues with speech synthesizers are expected as long as you're using a 
third party synth.
